// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atoshi/bridgeadapter/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryReceiptStateRequest struct {
}

func (m *QueryReceiptStateRequest) Reset()         { *m = QueryReceiptStateRequest{} }
func (m *QueryReceiptStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReceiptStateRequest) ProtoMessage()    {}
func (*QueryReceiptStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{2}
}
func (m *QueryReceiptStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReceiptStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReceiptStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReceiptStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReceiptStateRequest.Merge(m, src)
}
func (m *QueryReceiptStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReceiptStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReceiptStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReceiptStateRequest proto.InternalMessageInfo

type QueryReceiptStateResponse struct {
	State ReceiptState `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
	// pending_bridge is what tier judgments have authorised but Ethereum has not
	// yet confirmed, in ERC20 units. A figure that stays positive means receipts
	// are not arriving and the ATOX conversion rate has stopped advancing.
	PendingBridge cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=pending_bridge,json=pendingBridge,proto3,customtype=cosmossdk.io/math.Int" json:"pending_bridge"`
	// pending_project is the same figure for the project share.
	PendingProject cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=pending_project,json=pendingProject,proto3,customtype=cosmossdk.io/math.Int" json:"pending_project"`
}

func (m *QueryReceiptStateResponse) Reset()         { *m = QueryReceiptStateResponse{} }
func (m *QueryReceiptStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReceiptStateResponse) ProtoMessage()    {}
func (*QueryReceiptStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{3}
}
func (m *QueryReceiptStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReceiptStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReceiptStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReceiptStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReceiptStateResponse.Merge(m, src)
}
func (m *QueryReceiptStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReceiptStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReceiptStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReceiptStateResponse proto.InternalMessageInfo

func (m *QueryReceiptStateResponse) GetState() ReceiptState {
	if m != nil {
		return m.State
	}
	return ReceiptState{}
}

type QueryLimitsRequest struct {
}

func (m *QueryLimitsRequest) Reset()         { *m = QueryLimitsRequest{} }
func (m *QueryLimitsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryLimitsRequest) ProtoMessage()    {}
func (*QueryLimitsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{4}
}
func (m *QueryLimitsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLimitsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLimitsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLimitsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLimitsRequest.Merge(m, src)
}
func (m *QueryLimitsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryLimitsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLimitsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLimitsRequest proto.InternalMessageInfo

type QueryLimitsResponse struct {
	// outbound_* are the resolved outbound caps and what is left of them today.
	OutboundGlobalCap       cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=outbound_global_cap,json=outboundGlobalCap,proto3,customtype=cosmossdk.io/math.Int" json:"outbound_global_cap"`
	OutboundGlobalRemaining cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=outbound_global_remaining,json=outboundGlobalRemaining,proto3,customtype=cosmossdk.io/math.Int" json:"outbound_global_remaining"`
	OutboundLargeBudget     cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=outbound_large_budget,json=outboundLargeBudget,proto3,customtype=cosmossdk.io/math.Int" json:"outbound_large_budget"`
	OutboundLargeRemaining  cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=outbound_large_remaining,json=outboundLargeRemaining,proto3,customtype=cosmossdk.io/math.Int" json:"outbound_large_remaining"`
	PerAddressCap           cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=per_address_cap,json=perAddressCap,proto3,customtype=cosmossdk.io/math.Int" json:"per_address_cap"`
	SmallTransferThreshold  cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=small_transfer_threshold,json=smallTransferThreshold,proto3,customtype=cosmossdk.io/math.Int" json:"small_transfer_threshold"`
	MinTransferOut          cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=min_transfer_out,json=minTransferOut,proto3,customtype=cosmossdk.io/math.Int" json:"min_transfer_out"`
	CrisisMode              bool                  `protobuf:"varint,8,opt,name=crisis_mode,json=crisisMode,proto3" json:"crisis_mode,omitempty"`
	// inbound_* mirror the outbound pair for the bridge-in direction.
	InboundCap       cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=inbound_cap,json=inboundCap,proto3,customtype=cosmossdk.io/math.Int" json:"inbound_cap"`
	InboundRemaining cosmossdk_io_math.Int `protobuf:"bytes,10,opt,name=inbound_remaining,json=inboundRemaining,proto3,customtype=cosmossdk.io/math.Int" json:"inbound_remaining"`
	// resets_at_unix is when today's counters roll over (UTC midnight).
	//
	// The rate-limit day is a real 24 hours even on a test network, where
	// tokenomics compresses its own day to minutes -- the two are unrelated
	// clocks, and a client that assumes otherwise will show a reset that never
	// comes.
	ResetsAtUnix int64 `protobuf:"varint,11,opt,name=resets_at_unix,json=resetsAtUnix,proto3" json:"resets_at_unix,omitempty"`
	// migration_pool_balance is what the bps legs are computed against, returned
	// so a client can reproduce the caps rather than trust them.
	MigrationPoolBalance cosmossdk_io_math.Int `protobuf:"bytes,12,opt,name=migration_pool_balance,json=migrationPoolBalance,proto3,customtype=cosmossdk.io/math.Int" json:"migration_pool_balance"`
	// rate_limits_disabled mirrors the param. When true every figure above is
	// still reported -- they are what the limits WOULD be -- but nothing is
	// enforced. A UI that shows a quota bar must check this first, or it will
	// tell users they are near a cap that is not being applied.
	RateLimitsDisabled bool `protobuf:"varint,13,opt,name=rate_limits_disabled,json=rateLimitsDisabled,proto3" json:"rate_limits_disabled,omitempty"`
}

func (m *QueryLimitsResponse) Reset()         { *m = QueryLimitsResponse{} }
func (m *QueryLimitsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryLimitsResponse) ProtoMessage()    {}
func (*QueryLimitsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{5}
}
func (m *QueryLimitsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryLimitsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryLimitsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryLimitsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryLimitsResponse.Merge(m, src)
}
func (m *QueryLimitsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryLimitsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryLimitsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryLimitsResponse proto.InternalMessageInfo

func (m *QueryLimitsResponse) GetCrisisMode() bool {
	if m != nil {
		return m.CrisisMode
	}
	return false
}

func (m *QueryLimitsResponse) GetResetsAtUnix() int64 {
	if m != nil {
		return m.ResetsAtUnix
	}
	return 0
}

func (m *QueryLimitsResponse) GetRateLimitsDisabled() bool {
	if m != nil {
		return m.RateLimitsDisabled
	}
	return false
}

type QueryRateLimitStateRequest struct {
}

func (m *QueryRateLimitStateRequest) Reset()         { *m = QueryRateLimitStateRequest{} }
func (m *QueryRateLimitStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitStateRequest) ProtoMessage()    {}
func (*QueryRateLimitStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{6}
}
func (m *QueryRateLimitStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitStateRequest.Merge(m, src)
}
func (m *QueryRateLimitStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitStateRequest proto.InternalMessageInfo

type QueryRateLimitStateResponse struct {
	State RateLimitState `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
}

func (m *QueryRateLimitStateResponse) Reset()         { *m = QueryRateLimitStateResponse{} }
func (m *QueryRateLimitStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRateLimitStateResponse) ProtoMessage()    {}
func (*QueryRateLimitStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{7}
}
func (m *QueryRateLimitStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRateLimitStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRateLimitStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRateLimitStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRateLimitStateResponse.Merge(m, src)
}
func (m *QueryRateLimitStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRateLimitStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRateLimitStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRateLimitStateResponse proto.InternalMessageInfo

func (m *QueryRateLimitStateResponse) GetState() RateLimitState {
	if m != nil {
		return m.State
	}
	return RateLimitState{}
}

type QueryAddressUsageRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAddressUsageRequest) Reset()         { *m = QueryAddressUsageRequest{} }
func (m *QueryAddressUsageRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAddressUsageRequest) ProtoMessage()    {}
func (*QueryAddressUsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{8}
}
func (m *QueryAddressUsageRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressUsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressUsageRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressUsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressUsageRequest.Merge(m, src)
}
func (m *QueryAddressUsageRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressUsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressUsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressUsageRequest proto.InternalMessageInfo

func (m *QueryAddressUsageRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAddressUsageResponse struct {
	// used today by this address, outbound.
	Used cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=used,proto3,customtype=cosmossdk.io/math.Int" json:"used"`
	// remaining is per_address_cap - used, floored at zero.
	Remaining cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=remaining,proto3,customtype=cosmossdk.io/math.Int" json:"remaining"`
}

func (m *QueryAddressUsageResponse) Reset()         { *m = QueryAddressUsageResponse{} }
func (m *QueryAddressUsageResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAddressUsageResponse) ProtoMessage()    {}
func (*QueryAddressUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{9}
}
func (m *QueryAddressUsageResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAddressUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAddressUsageResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAddressUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAddressUsageResponse.Merge(m, src)
}
func (m *QueryAddressUsageResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAddressUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAddressUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAddressUsageResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "atoshi.bridgeadapter.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "atoshi.bridgeadapter.v1.QueryParamsResponse")
	proto.RegisterType((*QueryReceiptStateRequest)(nil), "atoshi.bridgeadapter.v1.QueryReceiptStateRequest")
	proto.RegisterType((*QueryReceiptStateResponse)(nil), "atoshi.bridgeadapter.v1.QueryReceiptStateResponse")
	proto.RegisterType((*QueryLimitsRequest)(nil), "atoshi.bridgeadapter.v1.QueryLimitsRequest")
	proto.RegisterType((*QueryLimitsResponse)(nil), "atoshi.bridgeadapter.v1.QueryLimitsResponse")
	proto.RegisterType((*QueryRateLimitStateRequest)(nil), "atoshi.bridgeadapter.v1.QueryRateLimitStateRequest")
	proto.RegisterType((*QueryRateLimitStateResponse)(nil), "atoshi.bridgeadapter.v1.QueryRateLimitStateResponse")
	proto.RegisterType((*QueryAddressUsageRequest)(nil), "atoshi.bridgeadapter.v1.QueryAddressUsageRequest")
	proto.RegisterType((*QueryAddressUsageResponse)(nil), "atoshi.bridgeadapter.v1.QueryAddressUsageResponse")
}

func init() {
	proto.RegisterFile("atoshi/bridgeadapter/v1/query.proto", fileDescriptor_88aa14ce8f0ccb90)
}

var fileDescriptor_88aa14ce8f0ccb90 = []byte{
	// 962 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0x8f, 0xdb, 0x64, 0xd3, 0x4c, 0xd2, 0xd0, 0x4c, 0xd3, 0xd6, 0x5d, 0xaa, 0xdd, 0xb0, 0xfc,
	0xe9, 0x42, 0xc0, 0x4e, 0xb6, 0x15, 0xea, 0x05, 0x89, 0x6c, 0x90, 0x50, 0x21, 0xa8, 0xc1, 0xa4,
	0x08, 0xa1, 0x0a, 0x6b, 0xbc, 0x1e, 0xbc, 0x03, 0xf6, 0x8c, 0x3b, 0x33, 0x8e, 0x52, 0x21, 0x2e,
	0x9c, 0x39, 0x20, 0x21, 0x3e, 0x02, 0x12, 0x27, 0xe8, 0xc7, 0xe8, 0xb1, 0x12, 0x17, 0xc4, 0xa1,
	0xaa, 0x12, 0x24, 0xbe, 0x01, 0x67, 0xe4, 0x99, 0xf1, 0x6e, 0x1c, 0xd6, 0x89, 0x97, 0xcb, 0x6a,
	0xfd, 0xe6, 0xfd, 0x7e, 0xef, 0xe7, 0xf7, 0x9e, 0xdf, 0x1b, 0xf0, 0x32, 0x92, 0x4c, 0x0c, 0x89,
	0x1b, 0x70, 0x12, 0x46, 0x18, 0x85, 0x28, 0x95, 0x98, 0xbb, 0xfb, 0x9b, 0xee, 0xc3, 0x0c, 0xf3,
	0x47, 0x4e, 0xca, 0x99, 0x64, 0xf0, 0x9a, 0x76, 0x72, 0x4a, 0x4e, 0xce, 0xfe, 0x66, 0x73, 0x05,
	0x25, 0x84, 0x32, 0x57, 0xfd, 0x6a, 0xdf, 0xe6, 0x6a, 0xc4, 0x22, 0xa6, 0xfe, 0xba, 0xf9, 0x3f,
	0x63, 0xbd, 0x11, 0x31, 0x16, 0xc5, 0xd8, 0x45, 0x29, 0x71, 0x11, 0xa5, 0x4c, 0x22, 0x49, 0x18,
	0x15, 0xe6, 0x74, 0xbd, 0x4a, 0x44, 0x39, 0xa0, 0x72, 0xee, 0xac, 0x02, 0xf8, 0x71, 0xae, 0x6d,
	0x17, 0x71, 0x94, 0x08, 0x0f, 0x3f, 0xcc, 0xb0, 0x90, 0x9d, 0x3d, 0x70, 0xb9, 0x64, 0x15, 0x29,
	0xa3, 0x02, 0xc3, 0x77, 0x40, 0x23, 0x55, 0x16, 0xdb, 0x5a, 0xb3, 0xba, 0x8b, 0xbd, 0xb6, 0x53,
	0xf1, 0x2a, 0x8e, 0x06, 0xf6, 0x67, 0x9f, 0x3c, 0x6b, 0xcf, 0x78, 0x06, 0xd4, 0x69, 0x02, 0x5b,
	0xb1, 0x7a, 0x78, 0x80, 0x49, 0x2a, 0x3f, 0x91, 0x48, 0xe2, 0x22, 0xe2, 0x3f, 0x16, 0xb8, 0x3e,
	0xe1, 0xd0, 0x04, 0xde, 0x02, 0x73, 0x22, 0x37, 0x98, 0xb8, 0xaf, 0x56, 0xc6, 0x3d, 0x8e, 0x36,
	0xd1, 0x35, 0x12, 0xde, 0x05, 0xcb, 0x29, 0xa6, 0x21, 0xa1, 0x91, 0xaf, 0x51, 0xf6, 0xb9, 0x35,
	0xab, 0xbb, 0xd0, 0xef, 0xe4, 0x4e, 0x7f, 0x3e, 0x6b, 0x5f, 0x19, 0x30, 0x91, 0x30, 0x21, 0xc2,
	0xaf, 0x1d, 0xc2, 0xdc, 0x04, 0xc9, 0xa1, 0x73, 0x97, 0xca, 0x5f, 0xfe, 0x7e, 0xfc, 0x86, 0xe5,
	0x5d, 0x34, 0xc8, 0xbe, 0x02, 0xc2, 0x0f, 0xc1, 0x0b, 0x05, 0x55, 0xca, 0xd9, 0x57, 0x78, 0x20,
	0xed, 0xf3, 0xb5, 0xb9, 0x0a, 0x15, 0xbb, 0x1a, 0x39, 0x2a, 0xc0, 0x0e, 0x49, 0x88, 0x1c, 0x15,
	0xe0, 0xf9, 0xbc, 0xa9, 0x40, 0x61, 0x36, 0x89, 0xf0, 0xc0, 0x65, 0x96, 0xc9, 0x80, 0x65, 0x34,
	0xf4, 0xa3, 0x98, 0x05, 0x28, 0xf6, 0x07, 0x28, 0x55, 0x69, 0xa9, 0x17, 0x7e, 0xa5, 0x80, 0xbf,
	0xaf, 0xd0, 0xdb, 0x28, 0x85, 0x5f, 0x80, 0xeb, 0x27, 0x39, 0x39, 0x4e, 0x10, 0xa1, 0x84, 0x46,
	0x53, 0x24, 0xe9, 0x5a, 0x99, 0xd9, 0x2b, 0x28, 0xe0, 0xa7, 0xe0, 0xca, 0x88, 0x3f, 0x46, 0x3c,
	0xc2, 0x7e, 0x90, 0x85, 0x11, 0x9e, 0x26, 0x69, 0xa3, 0x97, 0xde, 0xc9, 0xf1, 0x7d, 0x05, 0x87,
	0x0f, 0x80, 0x7d, 0x82, 0x77, 0x2c, 0x7b, 0xb6, 0x36, 0xf5, 0xd5, 0x12, 0xf5, 0x58, 0xf5, 0x07,
	0x79, 0x91, 0xb9, 0x8f, 0xc2, 0x90, 0x63, 0x21, 0x54, 0x96, 0xe7, 0xa6, 0x69, 0x18, 0xbe, 0xa5,
	0x91, 0x79, 0x86, 0x1f, 0x00, 0x5b, 0x24, 0x28, 0x8e, 0x7d, 0xc9, 0x11, 0x15, 0x5f, 0x62, 0xee,
	0xcb, 0x21, 0xc7, 0x62, 0xc8, 0xe2, 0xd0, 0x6e, 0xd4, 0x57, 0xaa, 0x38, 0xf6, 0x0c, 0xc5, 0x5e,
	0xc1, 0x00, 0x77, 0xc0, 0xa5, 0x84, 0xd0, 0x31, 0x37, 0xcb, 0xa4, 0x3d, 0x5f, 0xbf, 0x1f, 0x13,
	0x42, 0x0b, 0xce, 0x7b, 0x99, 0x84, 0x6d, 0xb0, 0x38, 0xe0, 0x44, 0x10, 0xe1, 0x27, 0x2c, 0xc4,
	0xf6, 0x85, 0x35, 0xab, 0x7b, 0xc1, 0x03, 0xda, 0xf4, 0x11, 0x0b, 0x31, 0xdc, 0x06, 0x8b, 0x84,
	0xea, 0xac, 0xe7, 0x49, 0x59, 0xa8, 0x1d, 0x09, 0x18, 0x58, 0x9e, 0x91, 0x7b, 0x60, 0xa5, 0x20,
	0x19, 0x17, 0x0d, 0xd4, 0xa6, 0xba, 0x64, 0xc0, 0xe3, 0x72, 0xbd, 0x02, 0x96, 0x39, 0x16, 0x58,
	0x0a, 0x1f, 0x49, 0x3f, 0xa3, 0xe4, 0xc0, 0x5e, 0x5c, 0xb3, 0xba, 0xe7, 0xbd, 0x25, 0x6d, 0xdd,
	0x92, 0xf7, 0x29, 0x39, 0x80, 0x9f, 0x81, 0xab, 0x09, 0x89, 0xb8, 0x1a, 0x97, 0x7e, 0xca, 0x58,
	0xec, 0x07, 0x28, 0x46, 0x74, 0x80, 0xed, 0xa5, 0xda, 0xb1, 0x57, 0x47, 0x0c, 0xbb, 0x8c, 0xc5,
	0x7d, 0x8d, 0x87, 0x1b, 0x60, 0x95, 0x23, 0x89, 0xfd, 0x58, 0x7d, 0xaf, 0x7e, 0x48, 0x04, 0x0a,
	0x62, 0x1c, 0xda, 0x17, 0x55, 0xfe, 0x60, 0x7e, 0xa6, 0x3f, 0xe5, 0xf7, 0xcc, 0x49, 0xe7, 0x06,
	0x68, 0xea, 0x81, 0x57, 0x1c, 0x95, 0xe6, 0x61, 0x00, 0x5e, 0x9c, 0x78, 0x6a, 0xe6, 0xc0, 0x76,
	0x79, 0x20, 0xde, 0xac, 0x1e, 0x88, 0x25, 0x7c, 0x69, 0x24, 0x76, 0x6e, 0x9b, 0x79, 0x6c, 0x3a,
	0xf5, 0xbe, 0x40, 0x51, 0x11, 0x1f, 0xda, 0x60, 0xde, 0xb4, 0xbe, 0x1e, 0x2e, 0x5e, 0xf1, 0xd8,
	0xf9, 0xa9, 0x98, 0xd4, 0x65, 0x98, 0x11, 0xf6, 0x36, 0x98, 0xcd, 0x04, 0x0e, 0xa7, 0x98, 0x48,
	0xca, 0x1f, 0xbe, 0x0b, 0x16, 0xfe, 0xcf, 0xd0, 0x19, 0x83, 0x7a, 0x8f, 0x1b, 0x60, 0x4e, 0xe9,
	0x82, 0xdf, 0x5b, 0xa0, 0xa1, 0x17, 0x10, 0x5c, 0xaf, 0x4c, 0xcc, 0x7f, 0xb7, 0x5e, 0xf3, 0xcd,
	0x7a, 0xce, 0xfa, 0x4d, 0x3b, 0x37, 0xbf, 0xfb, 0xfd, 0xaf, 0x1f, 0xcf, 0xbd, 0x04, 0xdb, 0x6e,
	0xd5, 0xbe, 0xd5, 0x6b, 0x4f, 0xc9, 0xd1, 0xb5, 0x3f, 0x4b, 0x4e, 0x69, 0x07, 0x9c, 0x25, 0xa7,
	0xbc, 0x19, 0x6a, 0xc8, 0xd1, 0xad, 0x09, 0x7f, 0xb5, 0xc0, 0x72, 0xb9, 0x2b, 0xe0, 0xad, 0xd3,
	0x23, 0x4d, 0xec, 0xd0, 0xe6, 0xed, 0xe9, 0x40, 0x46, 0xe6, 0xa6, 0x92, 0xb9, 0x0e, 0x5f, 0xaf,
	0x94, 0x39, 0xfe, 0x8c, 0x7c, 0xbd, 0xb9, 0x7f, 0xb3, 0xc0, 0xd2, 0xf1, 0x5e, 0x83, 0x9b, 0xa7,
	0x47, 0x9e, 0xd0, 0xce, 0xcd, 0xde, 0x34, 0x10, 0x23, 0xf5, 0x8e, 0x92, 0xda, 0x83, 0x1b, 0x95,
	0x52, 0x8b, 0xe5, 0x90, 0xe5, 0x38, 0xf7, 0x1b, 0xf3, 0xf8, 0x2d, 0xfc, 0xd9, 0x02, 0x4b, 0xc7,
	0x6f, 0x22, 0x67, 0x29, 0x9e, 0x70, 0x21, 0x3a, 0x4b, 0xf1, 0xa4, 0x6b, 0x52, 0xc7, 0x51, 0x8a,
	0xbb, 0xf0, 0xb5, 0xea, 0xe4, 0x6a, 0x98, 0xce, 0x6c, 0xdf, 0x7b, 0x72, 0xd8, 0xb2, 0x9e, 0x1e,
	0xb6, 0xac, 0xe7, 0x87, 0x2d, 0xeb, 0x87, 0xa3, 0xd6, 0xcc, 0xd3, 0xa3, 0xd6, 0xcc, 0x1f, 0x47,
	0xad, 0x99, 0xcf, 0xef, 0x44, 0x44, 0x0e, 0xb3, 0xc0, 0x19, 0xb0, 0xc4, 0x70, 0xbd, 0x35, 0x18,
	0x22, 0x42, 0x0b, 0xe2, 0xfd, 0xde, 0x86, 0x7b, 0x70, 0x82, 0x5e, 0x3e, 0x4a, 0xb1, 0x08, 0x1a,
	0xea, 0x5e, 0x79, 0xeb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0xe0, 0x7c, 0x1e, 0x0b, 0x0b,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters: the kill switch, the Ethereum-side
	// addresses and every rate-limit figure.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ReceiptState is what an auditor compares against the Ethereum vault: the
	// cumulative ERC20 confirmed here must equal what the vault reports having
	// released.
	// Limits reports the caps in force right now plus how much of each is left,
	// for both directions.
	//
	// Without it a client can read the params but not the usage, so the only
	// number it can show is the ceiling -- which looks identical whether the day
	// is untouched or nearly exhausted. That is the single most common reason a
	// rate limit is reported as "not working".
	Limits(ctx context.Context, in *QueryLimitsRequest, opts ...grpc.CallOption) (*QueryLimitsResponse, error)
	// RateLimitState is the raw daily counters, unresolved against the caps.
	RateLimitState(ctx context.Context, in *QueryRateLimitStateRequest, opts ...grpc.CallOption) (*QueryRateLimitStateResponse, error)
	// AddressUsage is one address's outbound usage today, for showing a per-user
	// remaining allowance.
	AddressUsage(ctx context.Context, in *QueryAddressUsageRequest, opts ...grpc.CallOption) (*QueryAddressUsageResponse, error)
	// ReceiptState returns the cumulative totals Ethereum has confirmed, plus the
	// app ids both message channels are addressed to.
	ReceiptState(ctx context.Context, in *QueryReceiptStateRequest, opts ...grpc.CallOption) (*QueryReceiptStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Limits(ctx context.Context, in *QueryLimitsRequest, opts ...grpc.CallOption) (*QueryLimitsResponse, error) {
	out := new(QueryLimitsResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/Limits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RateLimitState(ctx context.Context, in *QueryRateLimitStateRequest, opts ...grpc.CallOption) (*QueryRateLimitStateResponse, error) {
	out := new(QueryRateLimitStateResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/RateLimitState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AddressUsage(ctx context.Context, in *QueryAddressUsageRequest, opts ...grpc.CallOption) (*QueryAddressUsageResponse, error) {
	out := new(QueryAddressUsageResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/AddressUsage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReceiptState(ctx context.Context, in *QueryReceiptStateRequest, opts ...grpc.CallOption) (*QueryReceiptStateResponse, error) {
	out := new(QueryReceiptStateResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/ReceiptState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module parameters: the kill switch, the Ethereum-side
	// addresses and every rate-limit figure.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ReceiptState is what an auditor compares against the Ethereum vault: the
	// cumulative ERC20 confirmed here must equal what the vault reports having
	// released.
	// Limits reports the caps in force right now plus how much of each is left,
	// for both directions.
	//
	// Without it a client can read the params but not the usage, so the only
	// number it can show is the ceiling -- which looks identical whether the day
	// is untouched or nearly exhausted. That is the single most common reason a
	// rate limit is reported as "not working".
	Limits(context.Context, *QueryLimitsRequest) (*QueryLimitsResponse, error)
	// RateLimitState is the raw daily counters, unresolved against the caps.
	RateLimitState(context.Context, *QueryRateLimitStateRequest) (*QueryRateLimitStateResponse, error)
	// AddressUsage is one address's outbound usage today, for showing a per-user
	// remaining allowance.
	AddressUsage(context.Context, *QueryAddressUsageRequest) (*QueryAddressUsageResponse, error)
	// ReceiptState returns the cumulative totals Ethereum has confirmed, plus the
	// app ids both message channels are addressed to.
	ReceiptState(context.Context, *QueryReceiptStateRequest) (*QueryReceiptStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Limits(ctx context.Context, req *QueryLimitsRequest) (*QueryLimitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Limits not implemented")
}
func (*UnimplementedQueryServer) RateLimitState(ctx context.Context, req *QueryRateLimitStateRequest) (*QueryRateLimitStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateLimitState not implemented")
}
func (*UnimplementedQueryServer) AddressUsage(ctx context.Context, req *QueryAddressUsageRequest) (*QueryAddressUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressUsage not implemented")
}
func (*UnimplementedQueryServer) ReceiptState(ctx context.Context, req *QueryReceiptStateRequest) (*QueryReceiptStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiptState not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Limits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Limits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/Limits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Limits(ctx, req.(*QueryLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RateLimitState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RateLimitState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/RateLimitState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RateLimitState(ctx, req.(*QueryRateLimitStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AddressUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAddressUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AddressUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/AddressUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AddressUsage(ctx, req.(*QueryAddressUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReceiptState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReceiptStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReceiptState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/ReceiptState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReceiptState(ctx, req.(*QueryReceiptStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atoshi.bridgeadapter.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Limits",
			Handler:    _Query_Limits_Handler,
		},
		{
			MethodName: "RateLimitState",
			Handler:    _Query_RateLimitState_Handler,
		},
		{
			MethodName: "AddressUsage",
			Handler:    _Query_AddressUsage_Handler,
		},
		{
			MethodName: "ReceiptState",
			Handler:    _Query_ReceiptState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoshi/bridgeadapter/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReceiptStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReceiptStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReceiptStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryReceiptStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReceiptStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReceiptStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PendingProject.Size()
		i -= size
		if _, err := m.PendingProject.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PendingBridge.Size()
		i -= size
		if _, err := m.PendingBridge.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryLimitsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLimitsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLimitsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryLimitsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryLimitsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryLimitsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RateLimitsDisabled {
		i--
		if m.RateLimitsDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	{
		size := m.MigrationPoolBalance.Size()
		i -= size
		if _, err := m.MigrationPoolBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x62
	if m.ResetsAtUnix != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ResetsAtUnix))
		i--
		dAtA[i] = 0x58
	}
	{
		size := m.InboundRemaining.Size()
		i -= size
		if _, err := m.InboundRemaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.InboundCap.Size()
		i -= size
		if _, err := m.InboundCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	if m.CrisisMode {
		i--
		if m.CrisisMode {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.MinTransferOut.Size()
		i -= size
		if _, err := m.MinTransferOut.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.SmallTransferThreshold.Size()
		i -= size
		if _, err := m.SmallTransferThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.PerAddressCap.Size()
		i -= size
		if _, err := m.PerAddressCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.OutboundLargeRemaining.Size()
		i -= size
		if _, err := m.OutboundLargeRemaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.OutboundLargeBudget.Size()
		i -= size
		if _, err := m.OutboundLargeBudget.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.OutboundGlobalRemaining.Size()
		i -= size
		if _, err := m.OutboundGlobalRemaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.OutboundGlobalCap.Size()
		i -= size
		if _, err := m.OutboundGlobalCap.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryRateLimitStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRateLimitStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRateLimitStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAddressUsageRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressUsageRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressUsageRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAddressUsageResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAddressUsageResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAddressUsageResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Remaining.Size()
		i -= size
		if _, err := m.Remaining.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Used.Size()
		i -= size
		if _, err := m.Used.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReceiptStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryReceiptStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.PendingBridge.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.PendingProject.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryLimitsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryLimitsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OutboundGlobalCap.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.OutboundGlobalRemaining.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.OutboundLargeBudget.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.OutboundLargeRemaining.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.PerAddressCap.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.SmallTransferThreshold.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.MinTransferOut.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.CrisisMode {
		n += 2
	}
	l = m.InboundCap.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.InboundRemaining.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.ResetsAtUnix != 0 {
		n += 1 + sovQuery(uint64(m.ResetsAtUnix))
	}
	l = m.MigrationPoolBalance.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.RateLimitsDisabled {
		n += 2
	}
	return n
}

func (m *QueryRateLimitStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryRateLimitStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAddressUsageRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAddressUsageResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Used.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Remaining.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReceiptStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReceiptStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReceiptStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReceiptStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReceiptStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReceiptStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingBridge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingBridge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingProject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingProject.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLimitsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLimitsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLimitsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryLimitsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryLimitsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryLimitsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundGlobalCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutboundGlobalCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundGlobalRemaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutboundGlobalRemaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundLargeBudget", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutboundLargeBudget.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundLargeRemaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutboundLargeRemaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerAddressCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerAddressCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SmallTransferThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SmallTransferThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinTransferOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinTransferOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CrisisMode", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CrisisMode = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundCap", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InboundCap.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InboundRemaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InboundRemaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResetsAtUnix", wireType)
			}
			m.ResetsAtUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResetsAtUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationPoolBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MigrationPoolBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RateLimitsDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RateLimitsDisabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRateLimitStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRateLimitStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRateLimitStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressUsageRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressUsageRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressUsageRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAddressUsageResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAddressUsageResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAddressUsageResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Used", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Used.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remaining", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Remaining.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
