// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atoshi/bridgeadapter/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryReceiptStateRequest struct {
}

func (m *QueryReceiptStateRequest) Reset()         { *m = QueryReceiptStateRequest{} }
func (m *QueryReceiptStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReceiptStateRequest) ProtoMessage()    {}
func (*QueryReceiptStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{2}
}
func (m *QueryReceiptStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReceiptStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReceiptStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReceiptStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReceiptStateRequest.Merge(m, src)
}
func (m *QueryReceiptStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReceiptStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReceiptStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReceiptStateRequest proto.InternalMessageInfo

type QueryReceiptStateResponse struct {
	State ReceiptState `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
	// pending_bridge is what tier judgments have authorised but Ethereum has not
	// yet confirmed, in ERC20 units. A figure that stays positive means receipts
	// are not arriving and the ATOX conversion rate has stopped advancing.
	PendingBridge cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=pending_bridge,json=pendingBridge,proto3,customtype=cosmossdk.io/math.Int" json:"pending_bridge"`
	// pending_project is the same figure for the project share.
	PendingProject cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=pending_project,json=pendingProject,proto3,customtype=cosmossdk.io/math.Int" json:"pending_project"`
}

func (m *QueryReceiptStateResponse) Reset()         { *m = QueryReceiptStateResponse{} }
func (m *QueryReceiptStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReceiptStateResponse) ProtoMessage()    {}
func (*QueryReceiptStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88aa14ce8f0ccb90, []int{3}
}
func (m *QueryReceiptStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReceiptStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReceiptStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReceiptStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReceiptStateResponse.Merge(m, src)
}
func (m *QueryReceiptStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReceiptStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReceiptStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReceiptStateResponse proto.InternalMessageInfo

func (m *QueryReceiptStateResponse) GetState() ReceiptState {
	if m != nil {
		return m.State
	}
	return ReceiptState{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "atoshi.bridgeadapter.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "atoshi.bridgeadapter.v1.QueryParamsResponse")
	proto.RegisterType((*QueryReceiptStateRequest)(nil), "atoshi.bridgeadapter.v1.QueryReceiptStateRequest")
	proto.RegisterType((*QueryReceiptStateResponse)(nil), "atoshi.bridgeadapter.v1.QueryReceiptStateResponse")
}

func init() {
	proto.RegisterFile("atoshi/bridgeadapter/v1/query.proto", fileDescriptor_88aa14ce8f0ccb90)
}

var fileDescriptor_88aa14ce8f0ccb90 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x3f, 0x6f, 0x13, 0x31,
	0x14, 0x8f, 0x03, 0x8d, 0x84, 0xf9, 0x27, 0x4c, 0x11, 0xe1, 0x84, 0x2e, 0xe5, 0x10, 0x10, 0x51,
	0xb0, 0x49, 0x58, 0x58, 0x18, 0xc8, 0x56, 0xb1, 0x94, 0x83, 0x89, 0xa5, 0x72, 0x2e, 0xd6, 0xc5,
	0xc0, 0xf9, 0xb9, 0x67, 0x27, 0xa2, 0x2b, 0x33, 0x03, 0x12, 0x9f, 0x01, 0x89, 0x91, 0x4f, 0xc0,
	0xdc, 0xb1, 0x12, 0x0b, 0x62, 0xa8, 0x50, 0x82, 0xc4, 0x37, 0x60, 0x46, 0xb1, 0x7d, 0x52, 0x03,
	0x3d, 0x14, 0x96, 0x93, 0xf5, 0xfc, 0xfb, 0xf7, 0xde, 0x3b, 0xe3, 0xeb, 0xdc, 0x82, 0x19, 0x4b,
	0x36, 0x2c, 0xe5, 0x28, 0x17, 0x7c, 0xc4, 0xb5, 0x15, 0x25, 0x9b, 0xf6, 0xd8, 0xee, 0x44, 0x94,
	0x7b, 0x54, 0x97, 0x60, 0x81, 0x5c, 0xf6, 0x20, 0xba, 0x04, 0xa2, 0xd3, 0x5e, 0x74, 0x81, 0x17,
	0x52, 0x01, 0x73, 0x5f, 0x8f, 0x8d, 0xd6, 0x73, 0xc8, 0xc1, 0x1d, 0xd9, 0xe2, 0x14, 0xaa, 0x57,
	0x73, 0x80, 0xfc, 0x95, 0x60, 0x5c, 0x4b, 0xc6, 0x95, 0x02, 0xcb, 0xad, 0x04, 0x65, 0xc2, 0xed,
	0x66, 0x5d, 0x88, 0x65, 0x43, 0x07, 0x4e, 0xd6, 0x31, 0x79, 0xb2, 0xc8, 0xb6, 0xcd, 0x4b, 0x5e,
	0x98, 0x54, 0xec, 0x4e, 0x84, 0xb1, 0xc9, 0x33, 0x7c, 0x71, 0xa9, 0x6a, 0x34, 0x28, 0x23, 0xc8,
	0x43, 0xdc, 0xd2, 0xae, 0xd2, 0x46, 0x1b, 0xa8, 0x7b, 0xba, 0xdf, 0xa1, 0x35, 0xad, 0x50, 0x4f,
	0x1c, 0x9c, 0xdc, 0x3f, 0xec, 0x34, 0xd2, 0x40, 0x4a, 0x22, 0xdc, 0x76, 0xaa, 0xa9, 0xc8, 0x84,
	0xd4, 0xf6, 0xa9, 0xe5, 0x56, 0x54, 0x8e, 0xbf, 0x10, 0xbe, 0x72, 0xcc, 0x65, 0x30, 0x7e, 0x84,
	0xd7, 0xcc, 0xa2, 0x10, 0x7c, 0x6f, 0xd4, 0xfa, 0x1e, 0x65, 0x07, 0x77, 0xcf, 0x24, 0x5b, 0xf8,
	0x9c, 0x16, 0x6a, 0x24, 0x55, 0xbe, 0xe3, 0x59, 0xed, 0xe6, 0x06, 0xea, 0x9e, 0x1a, 0x24, 0x0b,
	0xd0, 0xb7, 0xc3, 0xce, 0xa5, 0x0c, 0x4c, 0x01, 0xc6, 0x8c, 0x5e, 0x52, 0x09, 0xac, 0xe0, 0x76,
	0x4c, 0xb7, 0x94, 0xfd, 0xf8, 0xf3, 0xd3, 0x6d, 0x94, 0x9e, 0x0d, 0xcc, 0x81, 0x23, 0x92, 0xc7,
	0xf8, 0x7c, 0x25, 0xa5, 0x4b, 0x78, 0x21, 0x32, 0xdb, 0x3e, 0xb1, 0xb2, 0x56, 0x95, 0x62, 0xdb,
	0x33, 0xfb, 0x9f, 0x9b, 0x78, 0xcd, 0x35, 0x4e, 0xde, 0x22, 0xdc, 0xf2, 0x73, 0x23, 0x9b, 0xb5,
	0x0d, 0xfe, 0xbd, 0xac, 0xe8, 0xce, 0x6a, 0x60, 0x3f, 0xca, 0xe4, 0xd6, 0x9b, 0x2f, 0x3f, 0xde,
	0x37, 0xaf, 0x91, 0x0e, 0xab, 0xfb, 0x4d, 0xfc, 0xb6, 0xc8, 0x07, 0x84, 0xcf, 0x1c, 0x1d, 0x27,
	0xe9, 0xfd, 0xdb, 0xe7, 0x98, 0xad, 0x46, 0xfd, 0xff, 0xa1, 0x84, 0x80, 0xd4, 0x05, 0xec, 0x92,
	0x9b, 0xb5, 0x01, 0x4b, 0x4f, 0xdb, 0x71, 0x8b, 0x1d, 0xa4, 0xfb, 0xb3, 0x18, 0x1d, 0xcc, 0x62,
	0xf4, 0x7d, 0x16, 0xa3, 0x77, 0xf3, 0xb8, 0x71, 0x30, 0x8f, 0x1b, 0x5f, 0xe7, 0x71, 0xe3, 0xf9,
	0x83, 0x5c, 0xda, 0xf1, 0x64, 0x48, 0x33, 0x28, 0x82, 0xd6, 0xdd, 0x6c, 0xcc, 0xa5, 0xaa, 0x84,
	0xa7, 0xfd, 0x7b, 0xec, 0xf5, 0x1f, 0xf2, 0x76, 0x4f, 0x0b, 0x33, 0x6c, 0xb9, 0xc7, 0x71, 0xff,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x98, 0x07, 0xdf, 0xbe, 0xd0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ReceiptState is what an auditor compares against the Ethereum vault: the
	// cumulative ERC20 confirmed here must equal what the vault reports having
	// released.
	ReceiptState(ctx context.Context, in *QueryReceiptStateRequest, opts ...grpc.CallOption) (*QueryReceiptStateResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReceiptState(ctx context.Context, in *QueryReceiptStateRequest, opts ...grpc.CallOption) (*QueryReceiptStateResponse, error) {
	out := new(QueryReceiptStateResponse)
	err := c.cc.Invoke(ctx, "/atoshi.bridgeadapter.v1.Query/ReceiptState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ReceiptState is what an auditor compares against the Ethereum vault: the
	// cumulative ERC20 confirmed here must equal what the vault reports having
	// released.
	ReceiptState(context.Context, *QueryReceiptStateRequest) (*QueryReceiptStateResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ReceiptState(ctx context.Context, req *QueryReceiptStateRequest) (*QueryReceiptStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiptState not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReceiptState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReceiptStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReceiptState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.bridgeadapter.v1.Query/ReceiptState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReceiptState(ctx, req.(*QueryReceiptStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atoshi.bridgeadapter.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ReceiptState",
			Handler:    _Query_ReceiptState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoshi/bridgeadapter/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReceiptStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReceiptStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReceiptStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryReceiptStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReceiptStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReceiptStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.PendingProject.Size()
		i -= size
		if _, err := m.PendingProject.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PendingBridge.Size()
		i -= size
		if _, err := m.PendingBridge.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReceiptStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryReceiptStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.PendingBridge.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.PendingProject.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReceiptStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReceiptStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReceiptStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReceiptStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReceiptStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReceiptStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingBridge", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingBridge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingProject", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PendingProject.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
