// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atoshi/tokenomics/v1/tokenomics.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params holds all governance-tunable parameters for the tokenomics module.
type Params struct {
	// miner_pool_total is the cap of the miner reward pool (10% of supply).
	MinerPoolTotal cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=miner_pool_total,json=minerPoolTotal,proto3,customtype=cosmossdk.io/math.Int" json:"miner_pool_total"`
	// project_pool_total is the cap of the project treasury pool (89% of supply).
	ProjectPoolTotal cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=project_pool_total,json=projectPoolTotal,proto3,customtype=cosmossdk.io/math.Int" json:"project_pool_total"`
	// migration_pool_total is the cap of the pre-mine migration pool (1% of supply).
	MigrationPoolTotal cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=migration_pool_total,json=migrationPoolTotal,proto3,customtype=cosmossdk.io/math.Int" json:"migration_pool_total"`
	// halving_interval_blocks is the number of blocks between block-reward halvings.
	HalvingIntervalBlocks int64 `protobuf:"varint,6,opt,name=halving_interval_blocks,json=halvingIntervalBlocks,proto3" json:"halving_interval_blocks,omitempty"`
	// initial_block_reward is the per-block miner reward before any halvings.
	InitialBlockReward cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=initial_block_reward,json=initialBlockReward,proto3,customtype=cosmossdk.io/math.Int" json:"initial_block_reward"`
	// price_base is the T0 USD price threshold (e.g. 0.15).
	PriceBase cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=price_base,json=priceBase,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price_base"`
	// volume_base is the T0 24h USD volume threshold (e.g. 150000).
	VolumeBase cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=volume_base,json=volumeBase,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"volume_base"`
	// tier_multiplier scales the price/volume threshold per tier (e.g. 1.1).
	TierMultiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=tier_multiplier,json=tierMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"tier_multiplier"`
	// consecutive_days_required is the streak length needed to trigger a release.
	ConsecutiveDaysRequired uint32 `protobuf:"varint,11,opt,name=consecutive_days_required,json=consecutiveDaysRequired,proto3" json:"consecutive_days_required,omitempty"`
	// release_percentage_bps is the share of circulating supply released per trigger.
	ReleasePercentageBps uint32 `protobuf:"varint,12,opt,name=release_percentage_bps,json=releasePercentageBps,proto3" json:"release_percentage_bps,omitempty"`
	// miner_release_share_bps is the share of each release that comes from the miner pool.
	MinerReleaseShareBps uint32 `protobuf:"varint,13,opt,name=miner_release_share_bps,json=minerReleaseShareBps,proto3" json:"miner_release_share_bps,omitempty"`
	// project_release_share_bps is the share that comes from the project pool.
	// miner + project share must equal 10000.
	ProjectReleaseShareBps uint32 `protobuf:"varint,14,opt,name=project_release_share_bps,json=projectReleaseShareBps,proto3" json:"project_release_share_bps,omitempty"`
	// project_treasury_address is unused.
	//
	// It used to be the only address allowed to withdraw against ProjectClaimable.
	// That withdrawal is gone -- the project's share of a tier release arrives as
	// ERC20 on Ethereum, and ProjectClaimable is the ceiling for refilling
	// migration_pool out of project_pool, not a balance anyone may draw. Kept as a
	// reserved field rather than removed so existing genesis files still parse.
	ProjectTreasuryAddress string `protobuf:"bytes,15,opt,name=project_treasury_address,json=projectTreasuryAddress,proto3" json:"project_treasury_address,omitempty"`
	// price_check_epoch_blocks is the MINIMUM number of blocks between two tier
	// samples.
	//
	// It used to mean "how often the EndBlocker evaluates the streak", i.e. the
	// chain picked the sampling instants. Under the daily-sampling rule the feeder
	// picks them, so this became a spacing floor instead: it stops a feeder from
	// spending the whole day's sample quota inside a few seconds, which would
	// collapse "three readings spread across 24h" into "three readings at one
	// instant" and let a momentary spike satisfy the day.
	//
	// Set it to roughly one_day / daily_samples. At 5s blocks and 3 samples that
	// is 5760 blocks (8h).
	PriceCheckEpochBlocks int64 `protobuf:"varint,16,opt,name=price_check_epoch_blocks,json=priceCheckEpochBlocks,proto3" json:"price_check_epoch_blocks,omitempty"`
	// day_seconds is how long a sampling "day" lasts.
	//
	// The release rule counts CONSECUTIVE DAYS, and a day is settled at the
	// boundary of this window, so the real time to a release is
	// consecutive_days_required * day_seconds. On mainnet this must be 86400 --
	// the rule is specified in calendar days.
	//
	// It is a parameter only so a test network can compress it. With the mainnet
	// value a testnet needs 30 real days to see one release, and even the reduced
	// consecutive_days_required used for testing still needs that many real day
	// boundaries, which makes the whole cross-chain path untestable in an
	// afternoon. Set it to a few minutes there.
	//
	// ⚠️ Changing it on a live chain rescales the streak: days already counted
	// were measured against the old window, and the ones after against the new
	// one, so "30 consecutive days" stops meaning one thing. Change it only
	// alongside a fresh genesis, or accept that the streak in progress is
	// meaningless.
	DaySeconds int64 `protobuf:"varint,22,opt,name=day_seconds,json=daySeconds,proto3" json:"day_seconds,omitempty"`
	// migration_refill_threshold_bps triggers a migration_pool refill.
	//
	// When migration_pool's balance drops below this fraction of
	// migration_pool_total, the EndBlocker moves ATOS in from project_pool, capped
	// by the ProjectClaimable authorisation. Design doc 1.4 calls this "半自动补充".
	//
	// The refill exists because migration_pool is the reserve behind the ordinary
	// user bridge: every bridge-in draws from it, and if it empties the bridge
	// stops accepting inbound transfers even though project_pool holds 8.7
	// trillion ATOS that tier releases have already authorised.
	//
	// Zero disables the refill.
	MigrationRefillThresholdBps uint32 `protobuf:"varint,21,opt,name=migration_refill_threshold_bps,json=migrationRefillThresholdBps,proto3" json:"migration_refill_threshold_bps,omitempty"`
	// daily_samples is how many readings per UTC day count as tier samples.
	//
	// Under ANY-of-N semantics this is the number of chances the price gets each
	// day, so it directly sets how permissive the rule is: raising it makes the
	// threshold easier to clear, not harder. Default 3.
	DailySamples int64 `protobuf:"varint,20,opt,name=daily_samples,json=dailySamples,proto3" json:"daily_samples,omitempty"`
	// migration_merkle_root is the hex-encoded Merkle root of the migration airdrop.
	MigrationMerkleRoot string `protobuf:"bytes,17,opt,name=migration_merkle_root,json=migrationMerkleRoot,proto3" json:"migration_merkle_root,omitempty"`
	// migration_claim_end_time_unix is the unix-time deadline after which migration
	// claims are rejected.
	MigrationClaimEndTimeUnix int64 `protobuf:"varint,18,opt,name=migration_claim_end_time_unix,json=migrationClaimEndTimeUnix,proto3" json:"migration_claim_end_time_unix,omitempty"`
	// validator_min_self_delegation is the chain-wide floor, in the base denom, on
	// a validator's own stake.
	//
	// The SDK's per-validator min_self_delegation cannot express this: a validator
	// declares its own value in MsgCreateValidator and the SDK only enforces that
	// its self-stake stays at or above whatever it declared, so declaring 1 opts
	// out entirely. This param is checked in the AnteHandler against both the
	// declared min_self_delegation and the initial self-stake, which makes the
	// SDK's existing machinery enforce the floor from then on: it unbonds any
	// validator whose self-stake falls below its declared minimum.
	//
	// Zero disables the check.
	ValidatorMinSelfDelegation cosmossdk_io_math.Int `protobuf:"bytes,19,opt,name=validator_min_self_delegation,json=validatorMinSelfDelegation,proto3,customtype=cosmossdk.io/math.Int" json:"validator_min_self_delegation"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53295d10b300f5a, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetHalvingIntervalBlocks() int64 {
	if m != nil {
		return m.HalvingIntervalBlocks
	}
	return 0
}

func (m *Params) GetConsecutiveDaysRequired() uint32 {
	if m != nil {
		return m.ConsecutiveDaysRequired
	}
	return 0
}

func (m *Params) GetReleasePercentageBps() uint32 {
	if m != nil {
		return m.ReleasePercentageBps
	}
	return 0
}

func (m *Params) GetMinerReleaseShareBps() uint32 {
	if m != nil {
		return m.MinerReleaseShareBps
	}
	return 0
}

func (m *Params) GetProjectReleaseShareBps() uint32 {
	if m != nil {
		return m.ProjectReleaseShareBps
	}
	return 0
}

func (m *Params) GetProjectTreasuryAddress() string {
	if m != nil {
		return m.ProjectTreasuryAddress
	}
	return ""
}

func (m *Params) GetPriceCheckEpochBlocks() int64 {
	if m != nil {
		return m.PriceCheckEpochBlocks
	}
	return 0
}

func (m *Params) GetDaySeconds() int64 {
	if m != nil {
		return m.DaySeconds
	}
	return 0
}

func (m *Params) GetMigrationRefillThresholdBps() uint32 {
	if m != nil {
		return m.MigrationRefillThresholdBps
	}
	return 0
}

func (m *Params) GetDailySamples() int64 {
	if m != nil {
		return m.DailySamples
	}
	return 0
}

func (m *Params) GetMigrationMerkleRoot() string {
	if m != nil {
		return m.MigrationMerkleRoot
	}
	return ""
}

func (m *Params) GetMigrationClaimEndTimeUnix() int64 {
	if m != nil {
		return m.MigrationClaimEndTimeUnix
	}
	return 0
}

// ReleaseState tracks the global price-unlock state machine.
type ReleaseState struct {
	CurrentTier          uint32                `protobuf:"varint,1,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	ConsecutiveDays      uint32                `protobuf:"varint,2,opt,name=consecutive_days,json=consecutiveDays,proto3" json:"consecutive_days,omitempty"`
	LastCheckBlock       int64                 `protobuf:"varint,3,opt,name=last_check_block,json=lastCheckBlock,proto3" json:"last_check_block,omitempty"`
	LastCheckTimeUnix    int64                 `protobuf:"varint,4,opt,name=last_check_time_unix,json=lastCheckTimeUnix,proto3" json:"last_check_time_unix,omitempty"`
	TotalMinerReleased   cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=total_miner_released,json=totalMinerReleased,proto3,customtype=cosmossdk.io/math.Int" json:"total_miner_released"`
	TotalProjectReleased cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=total_project_released,json=totalProjectReleased,proto3,customtype=cosmossdk.io/math.Int" json:"total_project_released"`
	// current_sample_day is the UTC day index (unix / 86400) being sampled.
	CurrentSampleDay int64 `protobuf:"varint,9,opt,name=current_sample_day,json=currentSampleDay,proto3" json:"current_sample_day,omitempty"`
	// samples_today counts the readings consumed as tier samples today, capped at
	// params.daily_samples. The cap matters under ANY-of-N semantics: without it,
	// a feeder reporting continuously would turn "the price held on three random
	// checks" into "the price touched the threshold at least once today", which is
	// a far weaker condition.
	SamplesToday uint32 `protobuf:"varint,10,opt,name=samples_today,json=samplesToday,proto3" json:"samples_today,omitempty"`
	// day_qualified is true once any sample today has cleared both thresholds.
	DayQualified bool `protobuf:"varint,11,opt,name=day_qualified,json=dayQualified,proto3" json:"day_qualified,omitempty"`
	// last_sampled_price_time is the timestamp of the oracle report last consumed
	// as a sample. A report is only sampled once -- without this the same report
	// would be re-counted every block until the next one arrived, burning the
	// day's quota in three consecutive blocks.
	LastSampledPriceTime int64 `protobuf:"varint,12,opt,name=last_sampled_price_time,json=lastSampledPriceTime,proto3" json:"last_sampled_price_time,omitempty"`
	// last_sample_block is the height at which the previous sample was taken, used
	// to enforce params.price_check_epoch_blocks as a minimum spacing.
	LastSampleBlock int64 `protobuf:"varint,13,opt,name=last_sample_block,json=lastSampleBlock,proto3" json:"last_sample_block,omitempty"`
}

func (m *ReleaseState) Reset()         { *m = ReleaseState{} }
func (m *ReleaseState) String() string { return proto.CompactTextString(m) }
func (*ReleaseState) ProtoMessage()    {}
func (*ReleaseState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53295d10b300f5a, []int{1}
}
func (m *ReleaseState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReleaseState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReleaseState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReleaseState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReleaseState.Merge(m, src)
}
func (m *ReleaseState) XXX_Size() int {
	return m.Size()
}
func (m *ReleaseState) XXX_DiscardUnknown() {
	xxx_messageInfo_ReleaseState.DiscardUnknown(m)
}

var xxx_messageInfo_ReleaseState proto.InternalMessageInfo

func (m *ReleaseState) GetCurrentTier() uint32 {
	if m != nil {
		return m.CurrentTier
	}
	return 0
}

func (m *ReleaseState) GetConsecutiveDays() uint32 {
	if m != nil {
		return m.ConsecutiveDays
	}
	return 0
}

func (m *ReleaseState) GetLastCheckBlock() int64 {
	if m != nil {
		return m.LastCheckBlock
	}
	return 0
}

func (m *ReleaseState) GetLastCheckTimeUnix() int64 {
	if m != nil {
		return m.LastCheckTimeUnix
	}
	return 0
}

func (m *ReleaseState) GetCurrentSampleDay() int64 {
	if m != nil {
		return m.CurrentSampleDay
	}
	return 0
}

func (m *ReleaseState) GetSamplesToday() uint32 {
	if m != nil {
		return m.SamplesToday
	}
	return 0
}

func (m *ReleaseState) GetDayQualified() bool {
	if m != nil {
		return m.DayQualified
	}
	return false
}

func (m *ReleaseState) GetLastSampledPriceTime() int64 {
	if m != nil {
		return m.LastSampledPriceTime
	}
	return 0
}

func (m *ReleaseState) GetLastSampleBlock() int64 {
	if m != nil {
		return m.LastSampleBlock
	}
	return 0
}

// BlockRewardState tracks how much of the miner pool has already been distributed.
type BlockRewardState struct {
	TotalDistributed cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=total_distributed,json=totalDistributed,proto3,customtype=cosmossdk.io/math.Int" json:"total_distributed"`
	CurrentPeriod    uint64                `protobuf:"varint,2,opt,name=current_period,json=currentPeriod,proto3" json:"current_period,omitempty"`
}

func (m *BlockRewardState) Reset()         { *m = BlockRewardState{} }
func (m *BlockRewardState) String() string { return proto.CompactTextString(m) }
func (*BlockRewardState) ProtoMessage()    {}
func (*BlockRewardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53295d10b300f5a, []int{2}
}
func (m *BlockRewardState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRewardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BlockRewardState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BlockRewardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRewardState.Merge(m, src)
}
func (m *BlockRewardState) XXX_Size() int {
	return m.Size()
}
func (m *BlockRewardState) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRewardState.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRewardState proto.InternalMessageInfo

func (m *BlockRewardState) GetCurrentPeriod() uint64 {
	if m != nil {
		return m.CurrentPeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "atoshi.tokenomics.v1.Params")
	proto.RegisterType((*ReleaseState)(nil), "atoshi.tokenomics.v1.ReleaseState")
	proto.RegisterType((*BlockRewardState)(nil), "atoshi.tokenomics.v1.BlockRewardState")
}

func init() {
	proto.RegisterFile("atoshi/tokenomics/v1/tokenomics.proto", fileDescriptor_e53295d10b300f5a)
}

var fileDescriptor_e53295d10b300f5a = []byte{
	// 1045 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcf, 0x4e, 0x1b, 0x47,
	0x18, 0xc7, 0xc5, 0x10, 0x33, 0x60, 0x58, 0x26, 0x06, 0x16, 0xa2, 0x18, 0x4a, 0x15, 0x89, 0x46,
	0x2d, 0x6e, 0xd2, 0xa6, 0xff, 0x4e, 0x2d, 0x10, 0x55, 0xa0, 0xa0, 0x38, 0x8b, 0x2b, 0x55, 0xbd,
	0x8c, 0xc6, 0x3b, 0x1f, 0xf6, 0x94, 0xd9, 0x9d, 0xcd, 0xcc, 0xd8, 0x65, 0x5f, 0xa1, 0xa7, 0x3e,
	0x46, 0x8f, 0x7d, 0x82, 0x9e, 0x73, 0xaa, 0x72, 0xac, 0x7a, 0x88, 0x2a, 0x38, 0xf4, 0x35, 0xa2,
	0x99, 0x59, 0xaf, 0x1d, 0x72, 0x31, 0x17, 0xcb, 0xfe, 0x7e, 0x7f, 0x66, 0xe7, 0x9b, 0xdf, 0x7c,
	0x5e, 0xf4, 0x80, 0x1a, 0xa9, 0xfb, 0xbc, 0x65, 0xe4, 0x05, 0xa4, 0x32, 0xe1, 0xb1, 0x6e, 0x0d,
	0x1f, 0x4d, 0xfc, 0xda, 0xcf, 0x94, 0x34, 0x12, 0x37, 0x3c, 0x6d, 0x7f, 0x02, 0x18, 0x3e, 0xda,
	0x5a, 0xa5, 0x09, 0x4f, 0x65, 0xcb, 0x7d, 0x7a, 0xe2, 0x56, 0xa3, 0x27, 0x7b, 0xd2, 0x7d, 0x6d,
	0xd9, 0x6f, 0xbe, 0xba, 0xfb, 0x17, 0x42, 0xf3, 0x6d, 0xaa, 0x68, 0xa2, 0xf1, 0x33, 0x14, 0x24,
	0x3c, 0x05, 0x45, 0x32, 0x29, 0x05, 0x31, 0xd2, 0x50, 0x11, 0x56, 0x76, 0x2a, 0x7b, 0x0b, 0x07,
	0xbb, 0xaf, 0xde, 0x6c, 0xcf, 0xfc, 0xfb, 0x66, 0x7b, 0x2d, 0x96, 0x3a, 0x91, 0x5a, 0xb3, 0x8b,
	0x7d, 0x2e, 0x5b, 0x09, 0x35, 0xfd, 0xfd, 0xe3, 0xd4, 0xfc, 0xf1, 0xff, 0x9f, 0x0f, 0x2b, 0xd1,
	0xb2, 0xd3, 0xb6, 0xa5, 0x14, 0x1d, 0xab, 0xc4, 0x6d, 0x84, 0x33, 0x25, 0x7f, 0x81, 0xd8, 0x4c,
	0xfa, 0x7d, 0x30, 0xb5, 0x5f, 0x50, 0xa8, 0xc7, 0x8e, 0x1d, 0xd4, 0x48, 0x78, 0x4f, 0x51, 0xc3,
	0x65, 0x3a, 0xe9, 0x39, 0x3b, 0xb5, 0x27, 0x2e, 0xf5, 0x63, 0xd7, 0x2f, 0xd1, 0x46, 0x9f, 0x8a,
	0x21, 0x4f, 0x7b, 0x84, 0xa7, 0x06, 0xd4, 0x90, 0x0a, 0xd2, 0x15, 0x32, 0xbe, 0xd0, 0xe1, 0xfc,
	0x4e, 0x65, 0x6f, 0x36, 0x5a, 0x2b, 0xe0, 0xe3, 0x02, 0x3d, 0x70, 0xa0, 0x7d, 0x1a, 0x9e, 0x72,
	0xc3, 0x47, 0x74, 0xa2, 0xe0, 0x57, 0xaa, 0x58, 0x78, 0x67, 0xfa, 0xa7, 0x29, 0xf4, 0xce, 0x30,
	0x72, 0x6a, 0xfc, 0x03, 0x42, 0x99, 0xe2, 0x31, 0x90, 0x2e, 0xd5, 0x10, 0xd6, 0x9c, 0xd7, 0x5e,
	0xe1, 0x75, 0xef, 0x7d, 0xaf, 0x67, 0xd0, 0xa3, 0x71, 0x7e, 0x04, 0xb1, 0x77, 0x5c, 0x70, 0xda,
	0x03, 0xaa, 0x01, 0x1f, 0xa3, 0xc5, 0xa1, 0x14, 0x83, 0xa4, 0x70, 0x5a, 0xb8, 0xa5, 0x13, 0xf2,
	0x62, 0x67, 0xf5, 0x02, 0xad, 0x18, 0x0e, 0x8a, 0x24, 0x03, 0x61, 0x78, 0x26, 0x38, 0xa8, 0x10,
	0xdd, 0xd2, 0x6e, 0xd9, 0x1a, 0x9c, 0x96, 0x7a, 0xfc, 0x2d, 0xda, 0x8c, 0x65, 0xaa, 0x21, 0x1e,
	0x18, 0x3e, 0x04, 0xc2, 0x68, 0xae, 0x89, 0x82, 0x97, 0x03, 0xae, 0x80, 0x85, 0x8b, 0x3b, 0x95,
	0xbd, 0x7a, 0xb4, 0x31, 0x41, 0x38, 0xa2, 0xb9, 0x8e, 0x0a, 0x18, 0x7f, 0x81, 0xd6, 0x15, 0x08,
	0xa0, 0x1a, 0x48, 0x06, 0x2a, 0x86, 0xd4, 0xd0, 0x1e, 0x90, 0x6e, 0xa6, 0xc3, 0x25, 0x27, 0x6c,
	0x14, 0x68, 0xbb, 0x04, 0x0f, 0x32, 0x8d, 0x9f, 0xa0, 0x0d, 0x1f, 0xee, 0x91, 0x56, 0xf7, 0xa9,
	0xf2, 0xb2, 0xba, 0x97, 0x39, 0x38, 0xf2, 0xe8, 0x99, 0x05, 0xad, 0xec, 0x1b, 0xb4, 0x39, 0x4a,
	0xf1, 0xfb, 0xc2, 0x65, 0x27, 0x5c, 0x2f, 0x08, 0x37, 0xa5, 0x5f, 0xa3, 0x70, 0x24, 0x35, 0x0a,
	0xa8, 0x1e, 0xa8, 0x9c, 0x50, 0xc6, 0x14, 0x68, 0x1d, 0xae, 0xd8, 0xfe, 0x95, 0xca, 0x4e, 0x01,
	0x7f, 0xef, 0x51, 0xfc, 0x95, 0x55, 0xda, 0x10, 0xc4, 0x7d, 0x88, 0x2f, 0x08, 0x64, 0x32, 0xee,
	0x8f, 0x32, 0x19, 0xf8, 0x4c, 0x3a, 0xfc, 0xd0, 0xc2, 0x4f, 0x2d, 0x5a, 0x64, 0x72, 0x1b, 0x2d,
	0x32, 0x9a, 0x13, 0x0d, 0xb1, 0x4c, 0x99, 0x0e, 0xd7, 0x1d, 0x17, 0x31, 0x9a, 0x9f, 0xf9, 0x0a,
	0x3e, 0x44, 0xcd, 0xf1, 0x15, 0x52, 0x70, 0xce, 0x85, 0x20, 0xa6, 0xaf, 0x40, 0xf7, 0xa5, 0x60,
	0x6e, 0x4f, 0x6b, 0x6e, 0x4f, 0xf7, 0x4a, 0x56, 0xe4, 0x48, 0x9d, 0x11, 0xc7, 0x6e, 0xec, 0x23,
	0x54, 0x67, 0x94, 0x8b, 0x9c, 0x68, 0x9a, 0x64, 0x02, 0x74, 0xd8, 0x70, 0xeb, 0x2c, 0xb9, 0xe2,
	0x99, 0xaf, 0xe1, 0xc7, 0x68, 0x6d, 0xbc, 0x52, 0x02, 0xea, 0x42, 0x00, 0x51, 0x52, 0x9a, 0x70,
	0xd5, 0x6d, 0xfd, 0x6e, 0x09, 0x9e, 0x3a, 0x2c, 0x92, 0xd2, 0xe0, 0xef, 0xd0, 0xfd, 0xb1, 0x26,
	0x16, 0x94, 0x27, 0x04, 0x52, 0x46, 0x0c, 0x4f, 0x80, 0x0c, 0x52, 0x7e, 0x19, 0x62, 0xb7, 0xd0,
	0x66, 0x49, 0x3a, 0xb4, 0x9c, 0xa7, 0x29, 0xeb, 0xf0, 0x04, 0x7e, 0x4c, 0xf9, 0x25, 0x06, 0x74,
	0x7f, 0x48, 0x05, 0x67, 0xd4, 0x48, 0x45, 0x12, 0x9e, 0x12, 0x0d, 0xe2, 0x9c, 0x30, 0x10, 0xd0,
	0x73, 0x82, 0xf0, 0xee, 0xd4, 0xb7, 0x73, 0xab, 0x34, 0x3a, 0xe5, 0xe9, 0x19, 0x88, 0xf3, 0xa3,
	0xd2, 0xe5, 0xa4, 0x5a, 0xab, 0x06, 0x73, 0x27, 0xd5, 0xda, 0x5c, 0x30, 0xbf, 0xfb, 0x77, 0x15,
	0x2d, 0x8d, 0x8e, 0xde, 0x50, 0x03, 0xf8, 0x43, 0xb4, 0x14, 0x0f, 0x94, 0x82, 0xd4, 0x10, 0x9b,
	0x7a, 0x37, 0x42, 0xeb, 0xd1, 0x62, 0x51, 0xeb, 0xd8, 0xf8, 0x7f, 0x8c, 0x82, 0x9b, 0xf1, 0x77,
	0x93, 0xb1, 0x1e, 0xad, 0xdc, 0x48, 0x3d, 0xde, 0x43, 0x81, 0xa0, 0xda, 0x14, 0x51, 0x70, 0x21,
	0x70, 0x03, 0x6f, 0x36, 0x5a, 0xb6, 0x75, 0x17, 0x01, 0x77, 0xfa, 0xb8, 0x85, 0x1a, 0x13, 0xcc,
	0x71, 0xd3, 0xaa, 0x8e, 0xbd, 0x5a, 0xb2, 0xcb, 0x66, 0x75, 0x50, 0xc3, 0x0d, 0x50, 0xf2, 0xce,
	0xc5, 0x60, 0xe1, 0xdc, 0xf4, 0x13, 0xcc, 0xe9, 0x4f, 0x27, 0x2e, 0x0e, 0xc3, 0x3f, 0xa1, 0x75,
	0xef, 0x7a, 0xe3, 0xde, 0x30, 0x37, 0x4e, 0xa7, 0xf3, 0xf5, 0xcf, 0xd5, 0x7e, 0xe7, 0x5e, 0x31,
	0xfc, 0x09, 0xc2, 0xa3, 0xc6, 0xfa, 0xe4, 0xd9, 0xc6, 0xb9, 0xc9, 0x36, 0x1b, 0x05, 0x05, 0xe2,
	0xe3, 0x77, 0x44, 0x73, 0x9b, 0xd2, 0x22, 0x9f, 0xc4, 0x48, 0x4b, 0x44, 0xae, 0xc1, 0x4b, 0x45,
	0xb1, 0x63, 0x6b, 0x3e, 0xca, 0x39, 0x79, 0x39, 0xa0, 0x82, 0x9f, 0xf3, 0x62, 0xf6, 0xd4, 0x6c,
	0x94, 0xf3, 0x17, 0xa3, 0x9a, 0x1d, 0x1d, 0xae, 0xb1, 0x5e, 0xc9, 0x88, 0xbf, 0x9b, 0xb6, 0xc1,
	0x6e, 0xe2, 0xcc, 0x46, 0xae, 0xef, 0x7e, 0x65, 0xd6, 0xb6, 0xa0, 0x6d, 0x31, 0x7e, 0x88, 0x56,
	0x27, 0x64, 0xc5, 0xd1, 0xd5, 0x9d, 0x60, 0x65, 0x2c, 0x70, 0x67, 0x77, 0x52, 0xad, 0xdd, 0x09,
	0x6a, 0x27, 0xd5, 0x5a, 0x2d, 0x58, 0xd8, 0xfd, 0xad, 0x82, 0x82, 0x89, 0xbf, 0x04, 0x1f, 0xaa,
	0xe7, 0x68, 0xd5, 0x77, 0x95, 0x71, 0x6d, 0x14, 0xef, 0x0e, 0x0c, 0xb0, 0x5b, 0xfc, 0x39, 0x07,
	0x4e, 0x7c, 0x34, 0xd6, 0xe2, 0x07, 0x68, 0x79, 0xd4, 0xcc, 0x0c, 0x14, 0x97, 0xcc, 0x05, 0xb0,
	0x1a, 0xd5, 0x8b, 0x6a, 0xdb, 0x15, 0x0f, 0x9e, 0xbf, 0xba, 0x6a, 0x56, 0x5e, 0x5f, 0x35, 0x2b,
	0xff, 0x5d, 0x35, 0x2b, 0xbf, 0x5f, 0x37, 0x67, 0x5e, 0x5f, 0x37, 0x67, 0xfe, 0xb9, 0x6e, 0xce,
	0xfc, 0xfc, 0xa4, 0xc7, 0x4d, 0x7f, 0xd0, 0xdd, 0x8f, 0x65, 0xd2, 0xf2, 0xaf, 0x20, 0x9f, 0xc6,
	0x7d, 0xca, 0xd3, 0xe2, 0x47, 0x6b, 0xf8, 0xf8, 0xb3, 0xd6, 0xe5, 0xe4, 0xcb, 0x8b, 0xc9, 0x33,
	0xd0, 0xdd, 0x79, 0xf7, 0xda, 0xf1, 0xf9, 0xdb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xfb, 0x0c,
	0xb0, 0xde, 0x08, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DaySeconds != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.DaySeconds))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.MigrationRefillThresholdBps != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.MigrationRefillThresholdBps))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.DailySamples != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.DailySamples))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	{
		size := m.ValidatorMinSelfDelegation.Size()
		i -= size
		if _, err := m.ValidatorMinSelfDelegation.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x9a
	if m.MigrationClaimEndTimeUnix != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.MigrationClaimEndTimeUnix))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if len(m.MigrationMerkleRoot) > 0 {
		i -= len(m.MigrationMerkleRoot)
		copy(dAtA[i:], m.MigrationMerkleRoot)
		i = encodeVarintTokenomics(dAtA, i, uint64(len(m.MigrationMerkleRoot)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	if m.PriceCheckEpochBlocks != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.PriceCheckEpochBlocks))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x80
	}
	if len(m.ProjectTreasuryAddress) > 0 {
		i -= len(m.ProjectTreasuryAddress)
		copy(dAtA[i:], m.ProjectTreasuryAddress)
		i = encodeVarintTokenomics(dAtA, i, uint64(len(m.ProjectTreasuryAddress)))
		i--
		dAtA[i] = 0x7a
	}
	if m.ProjectReleaseShareBps != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.ProjectReleaseShareBps))
		i--
		dAtA[i] = 0x70
	}
	if m.MinerReleaseShareBps != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.MinerReleaseShareBps))
		i--
		dAtA[i] = 0x68
	}
	if m.ReleasePercentageBps != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.ReleasePercentageBps))
		i--
		dAtA[i] = 0x60
	}
	if m.ConsecutiveDaysRequired != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.ConsecutiveDaysRequired))
		i--
		dAtA[i] = 0x58
	}
	{
		size := m.TierMultiplier.Size()
		i -= size
		if _, err := m.TierMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.VolumeBase.Size()
		i -= size
		if _, err := m.VolumeBase.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.PriceBase.Size()
		i -= size
		if _, err := m.PriceBase.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.InitialBlockReward.Size()
		i -= size
		if _, err := m.InitialBlockReward.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.HalvingIntervalBlocks != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.HalvingIntervalBlocks))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.MigrationPoolTotal.Size()
		i -= size
		if _, err := m.MigrationPoolTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.ProjectPoolTotal.Size()
		i -= size
		if _, err := m.ProjectPoolTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MinerPoolTotal.Size()
		i -= size
		if _, err := m.MinerPoolTotal.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ReleaseState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReleaseState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReleaseState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastSampleBlock != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.LastSampleBlock))
		i--
		dAtA[i] = 0x68
	}
	if m.LastSampledPriceTime != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.LastSampledPriceTime))
		i--
		dAtA[i] = 0x60
	}
	if m.DayQualified {
		i--
		if m.DayQualified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	if m.SamplesToday != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.SamplesToday))
		i--
		dAtA[i] = 0x50
	}
	if m.CurrentSampleDay != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.CurrentSampleDay))
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.TotalProjectReleased.Size()
		i -= size
		if _, err := m.TotalProjectReleased.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.TotalMinerReleased.Size()
		i -= size
		if _, err := m.TotalMinerReleased.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.LastCheckTimeUnix != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.LastCheckTimeUnix))
		i--
		dAtA[i] = 0x20
	}
	if m.LastCheckBlock != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.LastCheckBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.ConsecutiveDays != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.ConsecutiveDays))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentTier != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.CurrentTier))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlockRewardState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRewardState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRewardState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentPeriod != 0 {
		i = encodeVarintTokenomics(dAtA, i, uint64(m.CurrentPeriod))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.TotalDistributed.Size()
		i -= size
		if _, err := m.TotalDistributed.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTokenomics(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintTokenomics(dAtA []byte, offset int, v uint64) int {
	offset -= sovTokenomics(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinerPoolTotal.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.ProjectPoolTotal.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.MigrationPoolTotal.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	if m.HalvingIntervalBlocks != 0 {
		n += 1 + sovTokenomics(uint64(m.HalvingIntervalBlocks))
	}
	l = m.InitialBlockReward.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.PriceBase.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.VolumeBase.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.TierMultiplier.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	if m.ConsecutiveDaysRequired != 0 {
		n += 1 + sovTokenomics(uint64(m.ConsecutiveDaysRequired))
	}
	if m.ReleasePercentageBps != 0 {
		n += 1 + sovTokenomics(uint64(m.ReleasePercentageBps))
	}
	if m.MinerReleaseShareBps != 0 {
		n += 1 + sovTokenomics(uint64(m.MinerReleaseShareBps))
	}
	if m.ProjectReleaseShareBps != 0 {
		n += 1 + sovTokenomics(uint64(m.ProjectReleaseShareBps))
	}
	l = len(m.ProjectTreasuryAddress)
	if l > 0 {
		n += 1 + l + sovTokenomics(uint64(l))
	}
	if m.PriceCheckEpochBlocks != 0 {
		n += 2 + sovTokenomics(uint64(m.PriceCheckEpochBlocks))
	}
	l = len(m.MigrationMerkleRoot)
	if l > 0 {
		n += 2 + l + sovTokenomics(uint64(l))
	}
	if m.MigrationClaimEndTimeUnix != 0 {
		n += 2 + sovTokenomics(uint64(m.MigrationClaimEndTimeUnix))
	}
	l = m.ValidatorMinSelfDelegation.Size()
	n += 2 + l + sovTokenomics(uint64(l))
	if m.DailySamples != 0 {
		n += 2 + sovTokenomics(uint64(m.DailySamples))
	}
	if m.MigrationRefillThresholdBps != 0 {
		n += 2 + sovTokenomics(uint64(m.MigrationRefillThresholdBps))
	}
	if m.DaySeconds != 0 {
		n += 2 + sovTokenomics(uint64(m.DaySeconds))
	}
	return n
}

func (m *ReleaseState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentTier != 0 {
		n += 1 + sovTokenomics(uint64(m.CurrentTier))
	}
	if m.ConsecutiveDays != 0 {
		n += 1 + sovTokenomics(uint64(m.ConsecutiveDays))
	}
	if m.LastCheckBlock != 0 {
		n += 1 + sovTokenomics(uint64(m.LastCheckBlock))
	}
	if m.LastCheckTimeUnix != 0 {
		n += 1 + sovTokenomics(uint64(m.LastCheckTimeUnix))
	}
	l = m.TotalMinerReleased.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	l = m.TotalProjectReleased.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	if m.CurrentSampleDay != 0 {
		n += 1 + sovTokenomics(uint64(m.CurrentSampleDay))
	}
	if m.SamplesToday != 0 {
		n += 1 + sovTokenomics(uint64(m.SamplesToday))
	}
	if m.DayQualified {
		n += 2
	}
	if m.LastSampledPriceTime != 0 {
		n += 1 + sovTokenomics(uint64(m.LastSampledPriceTime))
	}
	if m.LastSampleBlock != 0 {
		n += 1 + sovTokenomics(uint64(m.LastSampleBlock))
	}
	return n
}

func (m *BlockRewardState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TotalDistributed.Size()
	n += 1 + l + sovTokenomics(uint64(l))
	if m.CurrentPeriod != 0 {
		n += 1 + sovTokenomics(uint64(m.CurrentPeriod))
	}
	return n
}

func sovTokenomics(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTokenomics(x uint64) (n int) {
	return sovTokenomics(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenomics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerPoolTotal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinerPoolTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectPoolTotal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProjectPoolTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationPoolTotal", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MigrationPoolTotal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HalvingIntervalBlocks", wireType)
			}
			m.HalvingIntervalBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HalvingIntervalBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialBlockReward", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InitialBlockReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceBase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriceBase.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VolumeBase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VolumeBase.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TierMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TierMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveDaysRequired", wireType)
			}
			m.ConsecutiveDaysRequired = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveDaysRequired |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReleasePercentageBps", wireType)
			}
			m.ReleasePercentageBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReleasePercentageBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinerReleaseShareBps", wireType)
			}
			m.MinerReleaseShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinerReleaseShareBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectReleaseShareBps", wireType)
			}
			m.ProjectReleaseShareBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProjectReleaseShareBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProjectTreasuryAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProjectTreasuryAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 16:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceCheckEpochBlocks", wireType)
			}
			m.PriceCheckEpochBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PriceCheckEpochBlocks |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationMerkleRoot", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MigrationMerkleRoot = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationClaimEndTimeUnix", wireType)
			}
			m.MigrationClaimEndTimeUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MigrationClaimEndTimeUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorMinSelfDelegation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorMinSelfDelegation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailySamples", wireType)
			}
			m.DailySamples = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DailySamples |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MigrationRefillThresholdBps", wireType)
			}
			m.MigrationRefillThresholdBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MigrationRefillThresholdBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaySeconds", wireType)
			}
			m.DaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaySeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTokenomics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenomics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReleaseState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenomics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReleaseState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReleaseState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentTier", wireType)
			}
			m.CurrentTier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentTier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsecutiveDays", wireType)
			}
			m.ConsecutiveDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsecutiveDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckBlock", wireType)
			}
			m.LastCheckBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastCheckBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCheckTimeUnix", wireType)
			}
			m.LastCheckTimeUnix = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastCheckTimeUnix |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalMinerReleased", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalMinerReleased.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalProjectReleased", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalProjectReleased.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentSampleDay", wireType)
			}
			m.CurrentSampleDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentSampleDay |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SamplesToday", wireType)
			}
			m.SamplesToday = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SamplesToday |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DayQualified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DayQualified = bool(v != 0)
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSampledPriceTime", wireType)
			}
			m.LastSampledPriceTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSampledPriceTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastSampleBlock", wireType)
			}
			m.LastSampleBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastSampleBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTokenomics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenomics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockRewardState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTokenomics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRewardState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRewardState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTokenomics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTokenomics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDistributed.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPeriod", wireType)
			}
			m.CurrentPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentPeriod |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTokenomics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTokenomics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTokenomics(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTokenomics
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTokenomics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTokenomics
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTokenomics
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTokenomics
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTokenomics        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTokenomics          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTokenomics = fmt.Errorf("proto: unexpected end of group")
)
