// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: atoshi/atox/v1/query.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGlobalStateRequest struct {
}

func (m *QueryGlobalStateRequest) Reset()         { *m = QueryGlobalStateRequest{} }
func (m *QueryGlobalStateRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalStateRequest) ProtoMessage()    {}
func (*QueryGlobalStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{2}
}
func (m *QueryGlobalStateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalStateRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalStateRequest.Merge(m, src)
}
func (m *QueryGlobalStateRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalStateRequest proto.InternalMessageInfo

type QueryGlobalStateResponse struct {
	State GlobalState `protobuf:"bytes,1,opt,name=state,proto3" json:"state"`
	// atox_supply is the live minted ATOX in aatox, always <= params.supply_cap.
	AtoxSupply cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=atox_supply,json=atoxSupply,proto3,customtype=cosmossdk.io/math.Int" json:"atox_supply"`
}

func (m *QueryGlobalStateResponse) Reset()         { *m = QueryGlobalStateResponse{} }
func (m *QueryGlobalStateResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGlobalStateResponse) ProtoMessage()    {}
func (*QueryGlobalStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{3}
}
func (m *QueryGlobalStateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGlobalStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGlobalStateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGlobalStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGlobalStateResponse.Merge(m, src)
}
func (m *QueryGlobalStateResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGlobalStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGlobalStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGlobalStateResponse proto.InternalMessageInfo

func (m *QueryGlobalStateResponse) GetState() GlobalState {
	if m != nil {
		return m.State
	}
	return GlobalState{}
}

type QueryAccountRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAccountRequest) Reset()         { *m = QueryAccountRequest{} }
func (m *QueryAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAccountRequest) ProtoMessage()    {}
func (*QueryAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{4}
}
func (m *QueryAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountRequest.Merge(m, src)
}
func (m *QueryAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountRequest proto.InternalMessageInfo

func (m *QueryAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryAccountResponse struct {
	Account AtoxAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account"`
	// atox_balance is the account's live aatox balance.
	AtoxBalance cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=atox_balance,json=atoxBalance,proto3,customtype=cosmossdk.io/math.Int" json:"atox_balance"`
	// unsettled is what settling now would add to pending:
	// atox_balance * (global_index - account.index).
	Unsettled cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=unsettled,proto3,customtype=cosmossdk.io/math.Int" json:"unsettled"`
	// claimable is pending + unsettled — what MsgClaimAtos would pay right now.
	Claimable cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=claimable,proto3,customtype=cosmossdk.io/math.Int" json:"claimable"`
	// can_claim is whether MsgClaimAtos would succeed right now. False alone is
	// ambiguous — see claim_blocked_reason for which of the several causes applies.
	CanClaim bool `protobuf:"varint,5,opt,name=can_claim,json=canClaim,proto3" json:"can_claim,omitempty"`
	// claim_blocked_reason explains a false can_claim in one machine-readable
	// token, so a wallet can show the right message instead of "nothing to claim"
	// for every cause:
	//
	//   ""                  can_claim is true
	//   "module_disabled"   params.enabled is false
	//   "module_account"    module accounts never accrue a conversion claim
	//   "nothing_to_claim"  the holder genuinely has no ATOX and no pending
	//   "pool_insufficient" the exchange pool cannot cover it yet — the claim is
	//                       owed and will succeed once a tier release funds it
	//
	// "pool_insufficient" is the one that must never be reported as
	// "nothing_to_claim": the holder IS owed, and telling them otherwise looks
	// like the chain lost their money.
	ClaimBlockedReason string `protobuf:"bytes,6,opt,name=claim_blocked_reason,json=claimBlockedReason,proto3" json:"claim_blocked_reason,omitempty"`
	// burn_on_settle is the aatox that settling right now would destroy. It equals
	// `unsettled` by construction (one aatox per liao), and is surfaced separately
	// because wallets need it to size a transfer.
	BurnOnSettle cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=burn_on_settle,json=burnOnSettle,proto3,customtype=cosmossdk.io/math.Int" json:"burn_on_settle"`
	// max_sendable is the largest ATOX transfer this account can sign right now:
	// atox_balance - burn_on_settle.
	//
	// Wallets must not offer `atox_balance` as "send max". A transfer settles the
	// sender first, which burns burn_on_settle aatox, so a send sized against the
	// displayed balance fails with insufficient funds for a reason the user cannot
	// see. The chain computes it here so every wallet gets the same answer.
	//
	// The transfer fee needs no headroom: it is INCLUSIVE, taken out of the amount
	// sent, so the recipient receives max_sendable minus the fee and the sender's
	// balance goes to zero.
	MaxSendable cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=max_sendable,json=maxSendable,proto3,customtype=cosmossdk.io/math.Int" json:"max_sendable"`
}

func (m *QueryAccountResponse) Reset()         { *m = QueryAccountResponse{} }
func (m *QueryAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAccountResponse) ProtoMessage()    {}
func (*QueryAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{5}
}
func (m *QueryAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAccountResponse.Merge(m, src)
}
func (m *QueryAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAccountResponse proto.InternalMessageInfo

func (m *QueryAccountResponse) GetAccount() AtoxAccount {
	if m != nil {
		return m.Account
	}
	return AtoxAccount{}
}

func (m *QueryAccountResponse) GetCanClaim() bool {
	if m != nil {
		return m.CanClaim
	}
	return false
}

func (m *QueryAccountResponse) GetClaimBlockedReason() string {
	if m != nil {
		return m.ClaimBlockedReason
	}
	return ""
}

type QueryExchangePoolRequest struct {
}

func (m *QueryExchangePoolRequest) Reset()         { *m = QueryExchangePoolRequest{} }
func (m *QueryExchangePoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryExchangePoolRequest) ProtoMessage()    {}
func (*QueryExchangePoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{6}
}
func (m *QueryExchangePoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryExchangePoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryExchangePoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryExchangePoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExchangePoolRequest.Merge(m, src)
}
func (m *QueryExchangePoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryExchangePoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExchangePoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExchangePoolRequest proto.InternalMessageInfo

type QueryExchangePoolResponse struct {
	// address of the atox_exchange_pool module account.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// balance currently held by the pool, in liao.
	Balance cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=balance,proto3,customtype=cosmossdk.io/math.Int" json:"balance"`
	// outstanding is total_pending: already settled and owed but not yet paid.
	// balance must always cover it.
	Outstanding cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=outstanding,proto3,customtype=cosmossdk.io/math.Int" json:"outstanding"`
}

func (m *QueryExchangePoolResponse) Reset()         { *m = QueryExchangePoolResponse{} }
func (m *QueryExchangePoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryExchangePoolResponse) ProtoMessage()    {}
func (*QueryExchangePoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e36e4b06f9e2d0de, []int{7}
}
func (m *QueryExchangePoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryExchangePoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryExchangePoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryExchangePoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryExchangePoolResponse.Merge(m, src)
}
func (m *QueryExchangePoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryExchangePoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryExchangePoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryExchangePoolResponse proto.InternalMessageInfo

func (m *QueryExchangePoolResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "atoshi.atox.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "atoshi.atox.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGlobalStateRequest)(nil), "atoshi.atox.v1.QueryGlobalStateRequest")
	proto.RegisterType((*QueryGlobalStateResponse)(nil), "atoshi.atox.v1.QueryGlobalStateResponse")
	proto.RegisterType((*QueryAccountRequest)(nil), "atoshi.atox.v1.QueryAccountRequest")
	proto.RegisterType((*QueryAccountResponse)(nil), "atoshi.atox.v1.QueryAccountResponse")
	proto.RegisterType((*QueryExchangePoolRequest)(nil), "atoshi.atox.v1.QueryExchangePoolRequest")
	proto.RegisterType((*QueryExchangePoolResponse)(nil), "atoshi.atox.v1.QueryExchangePoolResponse")
}

func init() { proto.RegisterFile("atoshi/atox/v1/query.proto", fileDescriptor_e36e4b06f9e2d0de) }

var fileDescriptor_e36e4b06f9e2d0de = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0x8d, 0xfb, 0x27, 0x69, 0x36, 0x55, 0xa5, 0xdf, 0xfe, 0x42, 0x71, 0xdd, 0xe2, 0x16, 0xb7,
	0x88, 0x14, 0x09, 0xbb, 0x2d, 0x48, 0x1c, 0xe0, 0x40, 0x53, 0x2a, 0xa8, 0x38, 0x50, 0x92, 0x1b,
	0x17, 0x6b, 0xe3, 0xac, 0x1c, 0xab, 0xf6, 0xae, 0x9b, 0x5d, 0x57, 0xa9, 0x10, 0x42, 0xe2, 0xc0,
	0x81, 0x13, 0x88, 0x0b, 0x1f, 0x81, 0x23, 0x57, 0xbe, 0x41, 0x8f, 0x95, 0xb8, 0x20, 0x0e, 0x15,
	0x6a, 0x91, 0xf8, 0x16, 0x08, 0x79, 0x77, 0x03, 0x89, 0x9b, 0x96, 0xf4, 0x12, 0xd9, 0xfb, 0xde,
	0x9b, 0x79, 0x33, 0x9e, 0x9d, 0x00, 0x03, 0x71, 0xca, 0x5a, 0x81, 0x83, 0x38, 0xed, 0x38, 0x7b,
	0xab, 0xce, 0x6e, 0x82, 0xdb, 0xfb, 0x76, 0xdc, 0xa6, 0x9c, 0xc2, 0x29, 0x89, 0xd9, 0x29, 0x66,
	0xef, 0xad, 0x1a, 0xff, 0xa1, 0x28, 0x20, 0xd4, 0x11, 0xbf, 0x92, 0x62, 0x94, 0x7d, 0xea, 0x53,
	0xf1, 0xe8, 0xa4, 0x4f, 0xea, 0x74, 0xce, 0xa7, 0xd4, 0x0f, 0xb1, 0x83, 0xe2, 0xc0, 0x41, 0x84,
	0x50, 0x8e, 0x78, 0x40, 0x09, 0x53, 0xe8, 0x4c, 0x26, 0xa5, 0x08, 0x2f, 0x20, 0xab, 0x0c, 0xe0,
	0xd3, 0xd4, 0xc0, 0x36, 0x6a, 0xa3, 0x88, 0xd5, 0xf0, 0x6e, 0x82, 0x19, 0xb7, 0x1e, 0x83, 0xff,
	0xfb, 0x4e, 0x59, 0x4c, 0x09, 0xc3, 0xf0, 0x36, 0xc8, 0xc7, 0xe2, 0x44, 0xd7, 0x16, 0xb4, 0x4a,
	0x69, 0x6d, 0xda, 0xee, 0xf7, 0x6b, 0x4b, 0x7e, 0x75, 0xec, 0xe0, 0x68, 0x3e, 0x57, 0x53, 0x5c,
	0x6b, 0x06, 0x5c, 0x16, 0xc1, 0x1e, 0x86, 0xb4, 0x81, 0xc2, 0x3a, 0x47, 0x1c, 0x77, 0xf3, 0x7c,
	0xd0, 0x80, 0x7e, 0x1a, 0x53, 0xd9, 0xee, 0x80, 0x71, 0x96, 0x1e, 0xa8, 0x64, 0xb3, 0xd9, 0x64,
	0x3d, 0x1a, 0x95, 0x51, 0xf2, 0xe1, 0x06, 0x28, 0xa5, 0x1c, 0x97, 0x25, 0x71, 0x1c, 0xee, 0xeb,
	0x23, 0x0b, 0x5a, 0xa5, 0x58, 0xb5, 0x52, 0xc6, 0xb7, 0xa3, 0xf9, 0x4b, 0x1e, 0x65, 0x11, 0x65,
	0xac, 0xb9, 0x63, 0x07, 0xd4, 0x89, 0x10, 0x6f, 0xd9, 0x5b, 0x84, 0x7f, 0xfc, 0xf9, 0xe9, 0x86,
	0x56, 0x03, 0xa9, 0xac, 0x2e, 0x54, 0x96, 0xa3, 0x5a, 0xb0, 0xee, 0x79, 0x34, 0x21, 0x5c, 0x39,
	0x86, 0x3a, 0x28, 0xa0, 0x66, 0xb3, 0x8d, 0x99, 0xec, 0x41, 0xb1, 0xd6, 0x7d, 0xb5, 0x7e, 0x8d,
	0x82, 0x72, 0xbf, 0x42, 0xd5, 0x71, 0x17, 0x14, 0x90, 0x3c, 0x3a, 0xab, 0x92, 0x75, 0x4e, 0x3b,
	0x4a, 0xa5, 0x2a, 0xe9, 0x2a, 0xe0, 0x26, 0x98, 0x14, 0xb5, 0x34, 0x50, 0x88, 0x88, 0x87, 0x2f,
	0x50, 0x8c, 0xe8, 0x41, 0x55, 0xca, 0xe0, 0x7d, 0x50, 0x4c, 0x08, 0xc3, 0x9c, 0x87, 0xb8, 0xa9,
	0x8f, 0x0e, 0x1d, 0xe3, 0xaf, 0x28, 0x8d, 0xe0, 0x85, 0x28, 0x88, 0x50, 0x23, 0xc4, 0xfa, 0xd8,
	0xf0, 0x11, 0xfe, 0x88, 0xe0, 0x2c, 0x28, 0x7a, 0x88, 0xb8, 0xe2, 0x40, 0x1f, 0x5f, 0xd0, 0x2a,
	0x13, 0xb5, 0x09, 0x0f, 0x91, 0x8d, 0xf4, 0x1d, 0xae, 0x80, 0xb2, 0x00, 0xdc, 0x46, 0x48, 0xbd,
	0x1d, 0xdc, 0x74, 0xdb, 0x18, 0x31, 0x4a, 0xf4, 0xbc, 0x68, 0x32, 0x14, 0x58, 0x55, 0x42, 0x35,
	0x81, 0xc0, 0x47, 0x60, 0xaa, 0x91, 0xb4, 0x89, 0x4b, 0x89, 0x2b, 0x3d, 0xea, 0x85, 0xa1, 0x5d,
	0x4d, 0xa6, 0xca, 0x27, 0xa4, 0x2e, 0x74, 0x69, 0x8f, 0x23, 0xd4, 0x71, 0x19, 0x26, 0x4d, 0x51,
	0xdd, 0xc4, 0xf0, 0x3d, 0x8e, 0x50, 0xa7, 0xae, 0x64, 0x96, 0xa1, 0x66, 0x79, 0xb3, 0xe3, 0xb5,
	0x10, 0xf1, 0xf1, 0x36, 0xa5, 0x61, 0x77, 0xd0, 0x3f, 0x6b, 0x60, 0x66, 0x00, 0xa8, 0x26, 0xe4,
	0xcc, 0xa1, 0x82, 0xf7, 0x40, 0xe1, 0xe2, 0x5f, 0xbe, 0x2b, 0x81, 0x0f, 0x40, 0x89, 0x26, 0x9c,
	0x71, 0x44, 0x9a, 0x01, 0xf1, 0x2f, 0xf0, 0xdd, 0x7b, 0x65, 0x6b, 0xef, 0xc6, 0xc0, 0xb8, 0xf0,
	0x0e, 0x77, 0x41, 0x5e, 0xde, 0x70, 0x68, 0x65, 0x47, 0xf8, 0xf4, 0x12, 0x31, 0x16, 0xcf, 0xe5,
	0xc8, 0xd2, 0x2d, 0xf3, 0xd5, 0x97, 0x1f, 0xef, 0x47, 0x74, 0x38, 0xed, 0x64, 0x76, 0x94, 0x5c,
	0x1e, 0xf0, 0xb5, 0x06, 0x4a, 0x3d, 0x17, 0x1d, 0x5e, 0x1f, 0x18, 0xf4, 0xf4, 0x6a, 0x31, 0x2a,
	0xff, 0x26, 0x2a, 0x0b, 0x4b, 0xc2, 0x82, 0x09, 0xe7, 0xb2, 0x16, 0x7c, 0x41, 0x76, 0xe5, 0x52,
	0x79, 0x09, 0x0a, 0xea, 0x8a, 0xc2, 0xc1, 0x85, 0xf5, 0x2f, 0x0a, 0x63, 0xe9, 0x7c, 0x92, 0xca,
	0xbd, 0x2c, 0x72, 0x2f, 0xc2, 0xab, 0xd9, 0xdc, 0xea, 0xfe, 0x3b, 0xcf, 0xd5, 0x24, 0xbc, 0x80,
	0x6f, 0x34, 0x30, 0xd9, 0x3b, 0x3d, 0x70, 0x70, 0x85, 0x03, 0xa6, 0xcf, 0x58, 0x1e, 0x82, 0xa9,
	0x0c, 0x5d, 0x13, 0x86, 0xe6, 0xe1, 0x95, 0xac, 0x21, 0xac, 0xd8, 0x6e, 0x4c, 0x69, 0x58, 0xdd,
	0x3a, 0x38, 0x36, 0xb5, 0xc3, 0x63, 0x53, 0xfb, 0x7e, 0x6c, 0x6a, 0x6f, 0x4f, 0xcc, 0xdc, 0xe1,
	0x89, 0x99, 0xfb, 0x7a, 0x62, 0xe6, 0x9e, 0x39, 0x7e, 0xc0, 0x5b, 0x49, 0xc3, 0xf6, 0x68, 0xa4,
	0x42, 0xdc, 0xf4, 0x5a, 0x28, 0x20, 0xdd, 0x78, 0x7b, 0x6b, 0x2b, 0x4e, 0x47, 0x46, 0xe5, 0xfb,
	0x31, 0x66, 0x8d, 0xbc, 0xf8, 0x23, 0xba, 0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x34, 0xe1,
	0xb5, 0x18, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters: the supply cap, the transfer fee rate
	// and the automatic-settlement batch size.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GlobalState returns the chain-wide conversion accounting: the global index,
	// the live ATOX supply and the two burn totals (conversion and transfer fee),
	// which are tracked apart because only the fee burn frees minting headroom.
	GlobalState(ctx context.Context, in *QueryGlobalStateRequest, opts ...grpc.CallOption) (*QueryGlobalStateResponse, error)
	// Account returns the raw settlement record plus the amount that would be
	// credited by settling right now. Wallets should show
	// `pending + unsettled` as the user's convertible balance.
	Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error)
	// ExchangePool reports the module account holding the ATOS that backs ATOX,
	// so anyone can verify solvency without trusting the running totals.
	ExchangePool(ctx context.Context, in *QueryExchangePoolRequest, opts ...grpc.CallOption) (*QueryExchangePoolResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/atoshi.atox.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GlobalState(ctx context.Context, in *QueryGlobalStateRequest, opts ...grpc.CallOption) (*QueryGlobalStateResponse, error) {
	out := new(QueryGlobalStateResponse)
	err := c.cc.Invoke(ctx, "/atoshi.atox.v1.Query/GlobalState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Account(ctx context.Context, in *QueryAccountRequest, opts ...grpc.CallOption) (*QueryAccountResponse, error) {
	out := new(QueryAccountResponse)
	err := c.cc.Invoke(ctx, "/atoshi.atox.v1.Query/Account", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ExchangePool(ctx context.Context, in *QueryExchangePoolRequest, opts ...grpc.CallOption) (*QueryExchangePoolResponse, error) {
	out := new(QueryExchangePoolResponse)
	err := c.cc.Invoke(ctx, "/atoshi.atox.v1.Query/ExchangePool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module parameters: the supply cap, the transfer fee rate
	// and the automatic-settlement batch size.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GlobalState returns the chain-wide conversion accounting: the global index,
	// the live ATOX supply and the two burn totals (conversion and transfer fee),
	// which are tracked apart because only the fee burn frees minting headroom.
	GlobalState(context.Context, *QueryGlobalStateRequest) (*QueryGlobalStateResponse, error)
	// Account returns the raw settlement record plus the amount that would be
	// credited by settling right now. Wallets should show
	// `pending + unsettled` as the user's convertible balance.
	Account(context.Context, *QueryAccountRequest) (*QueryAccountResponse, error)
	// ExchangePool reports the module account holding the ATOS that backs ATOX,
	// so anyone can verify solvency without trusting the running totals.
	ExchangePool(context.Context, *QueryExchangePoolRequest) (*QueryExchangePoolResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GlobalState(ctx context.Context, req *QueryGlobalStateRequest) (*QueryGlobalStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GlobalState not implemented")
}
func (*UnimplementedQueryServer) Account(ctx context.Context, req *QueryAccountRequest) (*QueryAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Account not implemented")
}
func (*UnimplementedQueryServer) ExchangePool(ctx context.Context, req *QueryExchangePoolRequest) (*QueryExchangePoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExchangePool not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.atox.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GlobalState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGlobalStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GlobalState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.atox.v1.Query/GlobalState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GlobalState(ctx, req.(*QueryGlobalStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Account_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Account(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.atox.v1.Query/Account",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Account(ctx, req.(*QueryAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ExchangePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryExchangePoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ExchangePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/atoshi.atox.v1.Query/ExchangePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ExchangePool(ctx, req.(*QueryExchangePoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "atoshi.atox.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GlobalState",
			Handler:    _Query_GlobalState_Handler,
		},
		{
			MethodName: "Account",
			Handler:    _Query_Account_Handler,
		},
		{
			MethodName: "ExchangePool",
			Handler:    _Query_ExchangePool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atoshi/atox/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGlobalStateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalStateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalStateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGlobalStateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGlobalStateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGlobalStateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AtoxSupply.Size()
		i -= size
		if _, err := m.AtoxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.State.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxSendable.Size()
		i -= size
		if _, err := m.MaxSendable.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.BurnOnSettle.Size()
		i -= size
		if _, err := m.BurnOnSettle.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if len(m.ClaimBlockedReason) > 0 {
		i -= len(m.ClaimBlockedReason)
		copy(dAtA[i:], m.ClaimBlockedReason)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClaimBlockedReason)))
		i--
		dAtA[i] = 0x32
	}
	if m.CanClaim {
		i--
		if m.CanClaim {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Claimable.Size()
		i -= size
		if _, err := m.Claimable.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Unsettled.Size()
		i -= size
		if _, err := m.Unsettled.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.AtoxBalance.Size()
		i -= size
		if _, err := m.AtoxBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Account.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryExchangePoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryExchangePoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryExchangePoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryExchangePoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryExchangePoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryExchangePoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Outstanding.Size()
		i -= size
		if _, err := m.Outstanding.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Balance.Size()
		i -= size
		if _, err := m.Balance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGlobalStateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGlobalStateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.State.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.AtoxSupply.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Account.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.AtoxBalance.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Unsettled.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Claimable.Size()
	n += 1 + l + sovQuery(uint64(l))
	if m.CanClaim {
		n += 2
	}
	l = len(m.ClaimBlockedReason)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.BurnOnSettle.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.MaxSendable.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryExchangePoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryExchangePoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = m.Balance.Size()
	n += 1 + l + sovQuery(uint64(l))
	l = m.Outstanding.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalStateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalStateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalStateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGlobalStateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGlobalStateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGlobalStateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.State.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtoxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AtoxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Account.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AtoxBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AtoxBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unsettled", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Unsettled.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Claimable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CanClaim", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.CanClaim = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimBlockedReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimBlockedReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnOnSettle", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnOnSettle.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSendable", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSendable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryExchangePoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryExchangePoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryExchangePoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryExchangePoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryExchangePoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryExchangePoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Outstanding", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Outstanding.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
