#!/usr/bin/env bash
#
# Docker-free equivalent of scripts/protocgen.sh, for machines where the
# proto-builder image is unavailable. Produces byte-identical output to
# `make proto-gen` (verified against x/energy, x/tokenomics and x/oracle).
#
# Plugin versions are pinned to go.mod so generated code cannot drift from
# the gogoproto runtime the chain links against.
#
# Scope defaults to proto/atoshi (our own modules). The inherited evmos protos
# were generated by an older gogoproto and regenerating them rewrites 30 files
# with descriptor-only churn, so they are excluded unless explicitly asked for:
#
#   make proto-gen-local              # proto/atoshi only
#   PROTO_SCOPE=./proto make proto-gen-local   # everything, incl. evmos
#
# Usage: make proto-gen-local
set -eo pipefail

PROTO_SCOPE="${PROTO_SCOPE:-./proto/atoshi}"

command -v buf >/dev/null || { echo "buf not found: brew install bufbuild/buf/buf"; exit 1; }
command -v protoc >/dev/null || { echo "protoc not found: brew install protobuf"; exit 1; }

GOBIN=$(go env GOPATH)/bin
export PATH="$GOBIN:$PATH"

GOGO_VER=$(go list -m -f '{{.Version}}' github.com/cosmos/gogoproto)
GW_VER=$(go list -m -f '{{.Version}}' github.com/grpc-ecosystem/grpc-gateway)

echo "Installing protoc plugins (gogoproto $GOGO_VER, grpc-gateway $GW_VER)"
go install "github.com/cosmos/gogoproto/protoc-gen-gocosmos@$GOGO_VER"
go install "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@$GW_VER"

echo "Generating gogo proto code from $PROTO_SCOPE"
proto_dirs=$(find "$PROTO_SCOPE" -path -prune -o -name '*.proto' -print0 | xargs -0 -n1 dirname | sort | uniq)
for dir in $proto_dirs; do
	for file in $(find "${dir}" -maxdepth 1 -name '*.proto'); do
		if grep -qE "option go_package.*(evmos|atoshi-chain)" "$file"; then
			buf generate --template proto/buf.gen.gogo.yaml "$file"
		fi
	done
done

# buf writes into the go_package path; lift it back into the repo root.
cp -r github.com/evmos/evmos/v*/* ./ 2>/dev/null || true
cp -r github.com/atoshi-chain/atoshi/v*/* ./ 2>/dev/null || true
rm -rf github.com

echo "Done. Review with: git diff --stat"
